### PR TITLE
Fix gamepad L2/R2 in games

### LINKED ISSUE #5362: AOA/UHID Gamepad Issues.
## Environment
 - Scrcpy 2.7 (prebuilt) on Windows 11.
 - samsung A52s 5G running A14 OneUI.

## Describe the bug

the way the UHID/AOA gamepad shows up messes up the input in some games.

on UHID it shows up as:

- Name: "scrcpy: Xbox One Controller"
- Product: "Vendor_0000_Product_0000"

and on AOA:

- Name: blank, it has no name.
- Product: "Vendor_ffff_Product_ffff"

so far ive had these issues in 2 games, Wuthering Waves and Human Fall Flat:

in human fall flat it straight up doesnt work, the inputs get ignored.
and in wuthering waves the triggers dont work (the game probably sees it as a generic controller).

but if i use LHLaurini's old controller build, it works just fine in both games, probably because it shows up as an actual Xbox controller:

- Name: "Microsoft X-Box 360 Pad"
- Product: "Vendor_045e_Product_028e"

so, what if you emulated an Xbox 360 or an Xbox One controller for Xinput and a PS4 controller for DInput?

after a lot of digging, i found `bool SDL_IsJoystickXInput(SDL_GUID guid)`, idk if its gonna be of any use to you though.

### PR DESCRIPTION
**Pull request by rom1v**
Fix #5362 (to be tested)

### CODE REVIEW

**Comment by Withoutruless** [comment]
it works perfectly (on uhid), thank you. 
I changed the vid:pid and the controller name to match an xbox 360 and thats it, no modifications required on android itself:

```diff 
public final class UhidManager {
         ByteBuffer buf = ByteBuffer.allocate(280 + reportDesc.length).order(ByteOrder.nativeOrder());
         buf.putInt(UHID_CREATE2);
 
-        String actualName = name.isEmpty() ? "scrcpy" : "scrcpy: " + name;
+        int vid = 0;
+        int pid = 0;
+        String actualName;
+        if ("Xbox One Controller".equals(name)) {
+            actualName = "Microsoft X-Box 360 Pad";
+            vid = 0x045e;
+            pid = 0x028e;
+        } else {
+            actualName = name.isEmpty() ? "scrcpy" : "scrcpy: " + name;
+        }
         byte[] utf8Name = actualName.getBytes(StandardCharsets.UTF_8);
         int len = StringUtils.getUtf8TruncationIndex(utf8Name, 127);
         assert len <= 127;
@@ -183,8 +192,8 @@ public final class UhidManager {
 
         buf.putShort((short) reportDesc.length);
         buf.putShort(BUS_VIRTUAL);
-        buf.putInt(0); // vendor id
-        buf.putInt(0); // product id
+        buf.putInt(vid); // vendor id
+        buf.putInt(pid); // product id
         buf.putInt(0); // version
         buf.putInt(0); // country;
         buf.put(reportDesc);
```

aoa is gonna be broken as long as we cant change the vid:pid on it (or you could revert back to the old descriptor for aoa).

im doing the "if ("Xbox One Controller".equals(name)){" check so i dont affect other devices like a mouse or a keyboard, i dont know if it would work for people with other controllers (or other os).

but here's the binary with that check removed if anyone wants to try it (probably breaks the uhid keyboard): 
[scrcpy-server.zip](https://github.com/user-attachments/files/18044673/scrcpy-server.zip)

**Comment by rom1v** [comment]
> I changed the vid:pid and the controller name to match an xbox 360 and thats it

What if you keep 0:0, does it also work?

**Comment by Withoutruless** [comment]
> > I changed the vid:pid and the controller name to match an xbox 360 and thats it
> 
> What if you keep 0:0, does it also work?

well, yes, but the rstick and triggers are reversed.

**Comment by rom1v** [comment]
> well, yes, but the rstick doesnt work and the triggers act as the rstick instead.

Is that also true with "Game Controller Tester" (`uk.co.powgames.gamecondiag`)? On my devices, it works correctly in Gamepad testers with 0:0.

Can it be related to your changes in .kl files? (https://github.com/Genymobile/scrcpy/issues/5362#issuecomment-2404529796)

**Comment by Withoutruless** [comment]
> > well, yes, but the rstick doesnt work and the triggers act as the rstick instead.
> 
> Is that also true with "Game Controller Tester" (`uk.co.powgames.gamecondiag`)? On my devices, it works correctly in Gamepad testers with 0:0.

yup, its the same, which gamepad(s) did you try? 

> Can it be related to your changes in .kl files? ([#5362 (comment)](https://github.com/Genymobile/scrcpy/issues/5362#issuecomment-2404529796))

nope, i reverted all of those changes, you dont need keylayout modifications to use xbox360 vid:pids with this update.

**Comment by rom1v** [comment]
> yup, its the same, which gamepad(s) did you try?

With a PS4 controller, but that should not make any difference, since scrcpy uses the events received from SDL to generate UHID events.

The difference is probably the drivers on the device. On my devices, it works correctly with both 0:0 or 045e:028e (but not with the ids of the PS4 controller, because it is expected to behave differently I guess).

**Comment by Withoutruless** [comment]
> The difference is probably the drivers on the device. On my devices, it works correctly with both 0:0 or 045e:028e (but not with the ids of the PS4 controller, because it is expected to behave differently I guess).

how do games react to input? do they see your gamepad as an xbox or a ps one?
some ps4 keylayouts use generic identifiers so thats probably the issue you're having i reckon.
you can try the dualsense one: Vendor=0x054c, Product=0x0ce6
its axis identifiers are identical to xbox's, buttons might not work though.

**Comment by rom1v** [comment]
With 054c:0ce6, in Gamepad Tester, it is detected as a "PS5 Controller".
The right stick and L2/R2 axis are inverted (right stick changes L2/R2, and vice-versa).

With 0:0 or 045e:028e, it works correctly.

**Comment by rom1v** [comment]
I will add an option `--gamepad-uhid-ids=xxxx:xxxx`, and use `045e:028e` by default.

**Comment by rom1v** [comment]
Or just force `045e:028e` without option (setting another value would not change the HID reports, so it makes no sense).

**Comment by rom1v** [comment]
I updated the PR.

Please test the latest version.

Here are binaries for Linux and Windows:

- [`scrcpy-linux-x86_64-gamepad_fixes.tar.gz`](https://tmp.rom1v.com/scrcpy/5623/2/scrcpy-linux-x86_64-gamepad_fixes.tar.gz) <sub>`SHA-256: f81fe2e3428018b403e401fd87483718ec2452b35f4586a7d8c612c4ccaac4d`</sub>
- [`scrcpy-win64-gamepad_fixes.zip`](https://tmp.rom1v.com/scrcpy/5623/2/scrcpy-win64-gamepad_fixes.zip) <sub>`SHA-256: 9e2f0a521ba191f8b098ccfc0c3f8ff3d406337c3849a076f754ecd0dfdaa53`</sub>

**Comment by rom1v** [comment]
@LHLaurini @yume-chan I'm also interested in your feedback if you have some time, since you worked on gamepads in the past 😉 Thank you.

**Comment by Withoutruless** [comment]
> I updated the PR.
> 
> Please test the latest version.
> 
> Here are binaries for Linux and Windows:
> 
> * [`scrcpy-linux-x86_64-gamepad_fixes.tar.gz`](https://tmp.rom1v.com/scrcpy/5623/2/scrcpy-linux-x86_64-gamepad_fixes.tar.gz) `SHA-256: f81fe2e3428018b403e401fd87483718ec2452b35f4586a7d8c612c4ccaac4d`
> * [`scrcpy-win64-gamepad_fixes.zip`](https://tmp.rom1v.com/scrcpy/5623/2/scrcpy-win64-gamepad_fixes.zip) `SHA-256: 9e2f0a521ba191f8b098ccfc0c3f8ff3d406337c3849a076f754ecd0dfdaa53`

it works perfectly, but i think we should change the controller name as well, since some games seem to pay attention to that:

``` diff
diff --git a/app/src/uhid/gamepad_uhid.c b/app/src/uhid/gamepad_uhid.c
index 2a063af5..b9016b39 100644
--- a/app/src/uhid/gamepad_uhid.c
+++ b/app/src/uhid/gamepad_uhid.c
@@ -36,7 +36,7 @@ sc_gamepad_uhid_send_open(struct sc_gamepad_uhid *gamepad,
     msg.uhid_create.id = hid_open->hid_id;
     msg.uhid_create.vendor_id = SC_GAMEPAD_UHID_VENDOR_ID;
     msg.uhid_create.product_id = SC_GAMEPAD_UHID_PRODUCT_ID;
-    msg.uhid_create.name = hid_open->name;
+    msg.uhid_create.name = "Microsoft X-Box 360 Pad";
     msg.uhid_create.report_desc = hid_open->report_desc;
     msg.uhid_create.report_desc_size = hid_open->report_desc_size;
 
diff --git a/server/src/main/java/com/genymobile/scrcpy/control/UhidManager.java b/server/src/main/java/com/genymobile/scrcpy/control/UhidManager.java
index 1d7678ec..c4867a3f 100644
--- a/server/src/main/java/com/genymobile/scrcpy/control/UhidManager.java
+++ b/server/src/main/java/com/genymobile/scrcpy/control/UhidManager.java
@@ -174,7 +174,7 @@ public final class UhidManager {
         ByteBuffer buf = ByteBuffer.allocate(280 + reportDesc.length).order(ByteOrder.nativeOrder());
         buf.putInt(UHID_CREATE2);
 
-        String actualName = name.isEmpty() ? "scrcpy" : "scrcpy: " + name;
+        String actualName = name.isEmpty() ? "scrcpy" : name;
         byte[] utf8Name = actualName.getBytes(StandardCharsets.UTF_8);
         int len = StringUtils.getUtf8TruncationIndex(utf8Name, 127);
         assert len <= 127;
```

**Comment by rom1v** [comment]
> i think we should change the controller name as well, since some games seem to pay attention to that

Did you observe a difference in behavior with just a different name?

If possible, I'd like to keep exposing the real controller name, but if it causes issues, ok.

**Comment by LHLaurini** [comment]
> Or just force `045e:028e` without option (setting another value would not change the HID reports, so it makes no sense to expose it).

I believe having that option would only be useful for games and controllers that support stuff like gyro, adaptive triggers and force feedback. While I did find some references online saying some games support these features, I didn't find which games support them. In any case, I don't think scrcpy currently supports these features anyway, so it doesn't matter for now.

**Comment by Withoutruless** [comment]
> > i think we should change the controller name as well, since some games seem to pay attention to that
> 
> Did you observe a difference in behavior with just a different name?

yes, in human fall flat ([#5362](https://github.com/Genymobile/scrcpy/issues/5362#issuecomment-2404692286)), the game didnt recognize the controller cause of its name, changing the name fixed the issue.

**Comment by rom1v** [comment]
@Withoutruless Thank you :+1: I added a commit under your authorship: 7418fd06626a2ae405f4bfbe9980a9c4ebd744a7.

(and I added a log when a gamepad is added or removed: 548d2c755fa285369735b693adc34cab3c55e9cf)

**Comment by rom1v** [comment]
(scrcpy 3.1 including this PR is ready. I will publish it soon :rocket:)

**Comment by DomitoriKor** [comment]
@rom1v Hello! It seems there's still a problem with some gamepads. The triggers on Logitech F310 don't work in either mode, and the Y and X buttons are for some reason swapped. Tested on 3.1 release version and gamepad_fixes version from this conversation. Could you please look into it?

**Pull request merged**
