### PR TITLE
Add OTG support for Windows

### PR DESCRIPTION
**Pull request by rom1v**
[scrcpy v1.22](https://github.com/Genymobile/scrcpy/releases/tag/v1.22) introduced a new [OTG mode](https://github.com/Genymobile/scrcpy#otg). It was based on HID keyboard introduced in [v1.20](https://github.com/Genymobile/scrcpy/releases/tag/v1.20) and HID mouse also introduced in v1.22. It was only supported on Linux.

On Windows, it is not possible to open a USB device if it is already open by another process (like the adb daemon). As a consequence, we can't send HID events if adb is running. Therefore, on Windows, `--hid-keyboard` and `--hid-mouse` while mirroring are not possible. These features are still limited to Linux.

However, in OTG mode (`--otg`), no adb is necessary, so it is possible to open the USB device to send HID events. This PR adds support for `--otg` on Windows.

Concretely:
 - download the unofficial release below
 - extract it
 - double-click on `open_a_terminal_here.bat` (extracted from the release)
 - plug an Android device over USB
 - execute `scrcpy --otg`

Fixes https://github.com/Genymobile/scrcpy/issues/2773

---

Here is an unofficial release with this branch, so that you can test and report issues:
 - [`scrcpy-otg-windows-win64.zip`](https://tmp.rom1v.com/scrcpy/3011/1/scrcpy-win64-otg-windows.zip) _sha256:6cb1a9e01441fedb9618fa98b8403aecbed39bc7167e8edd3f44fb6227591b8d_
 - ~[`scrcpy-otg-windows-win32.zip`](https://tmp.rom1v.com/scrcpy/3011/1/scrcpy-win32-otg-windows.zip) _sha256:38a397086999c51ff8634915dd3c1f0792587aeccdd6a65961a841a9e5d87db3_~

Note that on my test computer with Windows 10 64bit, the win32 version does not work due to missing `libgcc_s_sjlj-1.dll`.
According to [stackoverflow](https://stackoverflow.com/questions/12921911/mingw-libgcc-s-sjlj-1-dll-is-missing), a linker flag `-static-libgcc` must be added somewhere, but I think it is related to prebuilt libusb dll for win32 (since it works for win64).

EDIT: yes, it's a problem on the libusb prebuilt dll for win32: https://github.com/libusb/libusb/issues/1049

### CODE REVIEW

**Comment by rom1v** [comment]
I disabled the feature for win32 due to this prebuilt dll issue. On Win64, it works as expected. I merge. :rocket:

**Comment by rom1v** [comment]
There is a PR for GitHub Actions: #1709
But for some reason, `gradle check` didn't work and had to be removed for the CI.

I spend some time to figure out why, but didn't manage to make it work, then I worked on something else… I should retry (any help is welcome).

**Comment by 54m33r4** [comment]
DEBUG: Open USB device 04e8:6860: libusb error: Operation not supported or unimplemented on this platform

any workarounds? Running Android 11 on the device and also compatible with both OTG mouse and kb too. but not in scrcpy?

**Comment by rom1v** [comment]
> Operation not supported or unimplemented on this platform

That might be an error on another USB device (that's why it's logged at debug level).

Is the device detected by adb (when USB debugging is enabled)?

Is your dev

**Comment by 54m33r4** [comment]
> > Operation not supported or unimplemented on this platform
> 
> That might be an error on another USB device (that's why it's logged at debug level).
> 
> Is the device detected by adb (when USB debugging is enabled)?
> 
> PS: please post console output as text instead of screenshot.

Yes ,everything else works perfectly except just the OTG function and it says no USB devices. even if I connected multiple devices, the new error screen shows this as a USB device... could windows 11 be a problem?

**Comment by rom1v** [comment]
@54m33r4 #3050

**Pull request merged**
