### PR TITLE
Adding new option --encoder-name

### PR DESCRIPTION
**Pull request by tzah4748**
Relates to issue https://github.com/Genymobile/scrcpy/issues/1810

It seems that some devices have more than one encoder, some encoders may cause issues or crash.
With this option we can specify which encoder we want the device to use.

Proved useful for the device in the issue.

### CODE REVIEW

**Comment by tzah4748** [comment]
@rom1v did you get a chance to take a look?

**Comment by rom1v** [comment]
Sorry, not yet in details. Currently, I have no time to work on scrcpy.

But I have it in mind (and in my todo list), and this option will be merged before a new release.

One additional thing I would like to add is listing the available encoder names on error (like ``--display`

**Comment by rom1v** [comment]
I rebased on current `dev`, I changed the option `--encoder-name` to `--encoder` (for simplicity and consistency with `--display` to select the display id) and some minor other changed on your commit.
Then I added another commit to list the available encoders if an invalid name is passed.

Please review and test: [`encoder_name`](https://github.com/Genymobile/scrcpy/commits/encoder_name)

If it's ok, I'll merge into `dev` :)

**Comment by tzah4748** [comment]
Looks good to me!
Feel free to merge it.

**Comment by rom1v** [comment]
Merged into `dev`, thanks :+1:

**Comment by rom1v** [comment]
Here are binaries for the current `dev` branch including this feature (it will be helpful to debug other issues).

For windows users, take both `scrcpy.exe` and `scrcpy-server`, and replace them in your scrcpy v1.16 release.

For other platforms, take `scrcpy-server` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) only the client.

- [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1827/1/scrcpy.exe)
  _SHA256: f0079664dc8954f62a486346d2267c6159d7cd47d0527d117f3c73350d2bb053_
- [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1827/1/scrcpy-server)
  _SHA256: 1230ccd507e20a0ed0a307cd760968240b451de47a19cb2daaa3a5450893b7f9_

(to replace in v1.16 release)

**Pull request closed without merging**
