### PR TITLE
Adding an option for disabling screen saver

### PR DESCRIPTION
**Pull request by axxie**

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1: Will test and merge later.

Ref #1370

**Comment by rom1v** [comment]
Thank you. I rebased onto `dev`, replaced `screen-saver` by `screensaver` everywhere, and added a section in the README.

Please review the commit: https://github.com/Genymobile/scrcpy/commits/pr1502 :)

If it's ok, I merge it into `dev`.

**Comment by axxie** [comment]
The commit seems to be ok

**Comment by rom1v** [comment]
Thank you. Merged :+1:

**Pull request closed without merging**
