### PR TITLE
Document Windows command line usage

### PR DESCRIPTION
**Pull request by rom1v**
I wrote a very small tutorial for Windows users who don't know how to use the command line.

Rendered: https://github.com/Genymobile/scrcpy/blob/wincli/FAQ.md#command-line-on-windows

Reviews welcome.

### CODE REVIEW

**Review by npes87184 — APPROVED** [review]
Reviewed-by: Yu-Chen Lin <npes87184@gmail.com>

**Comment by npes87184** [comment]
For me, this tutorial is good enough. However, I don't know that "actual" users who are only familiar with GUI can understand or not.

If users still struggle on this, maybe the next steps is to add pictures...

**Comment by PonyPC** [comment]
Considering add GUI just like this: https://anl.ink AnLink. It seems uses scrcpy technology but provide a user friendly UI and guide for common users.

**Comment by rom1v** [comment]
Thank you @npes87184 :+1:

Merged: 43d3dcbd970640c70272fac9d5e54ff90f8e5eea

**Pull request closed without merging**
