### PR TITLE
Update macos.md

### PR DESCRIPTION
**Pull request by Gutem**
update brew command

### CODE REVIEW

**Comment by rom1v** [comment]
OK, so finally `--cask` is necessary? (cf this thread: https://github.com/Genymobile/scrcpy/pull/2231#issuecomment-812552226)

**Comment by rom1v** [comment]
cc @quyleanh (#2231) @clesiemo3 (#2004)

**Comment by Gutem** [comment]
> OK, so finally `--cask` is necessary? (cf this thread: [#2231 (comment)](https://github.com/Genymobile/scrcpy/pull/2231#issuecomment-812548167))

At least, on OSX 15.0.1 Sequoia, `--cask` was the only way to install `android-platform-tools`

**Comment by quyleanh** [comment]
Hmm. I'm using `macOS 13.7 (22H123)` now and the `brew` command without `--cask` is still working. With `--cask` command works too. So I think this commit is fine.

**Comment by rom1v** [comment]
Merged into `master`: f1f27116269ecbe422fd853ec192e3a80e168f76

**Pull request closed without merging**
