### PR TITLE
Add shortcuts to rotate client window

### PR DESCRIPTION
**Pull request by rom1v**
Add `Ctrl+Left` and `Ctrl`+`Right` shortcuts to rotate the scrcpy window.

Contrary to `--lock-video-orientation` (#1151), the rotation has no impact on recording, and can be changed dynamically (and immediately).

This provides an alternative solution for #218.

There are now 3 different (cumulative) rotations:
 - `Ctrl`+`r` to request the device to rotate between portrait and landscape
 - `--lock-video-orientation` to force a mirroring/recording orientation
 - `Ctrl`+`←` and `Ctrl`+`→` to rotate the scrcpy window

Please review/test on your platform :) Feedbacks welcome.

I'll probably merge in `dev` soon.

Thank you

### CODE REVIEW

**Comment by dre-z17** [comment]
My phone must be a piece. 

Screen rotation works with all apps _other than my built in camera app_. The SCRCPY window within my PC refuses to rotate out of vertical portrait layout to a horizontal landscape layout. 

I've attached screenshot. The image shows multiple 'request to rotate' msgs but nothing happens. 

Hopefully a screenshot doesn't violate tos :(
no landscape

Maybe I failed to uninstall the old build correctly(?). Will keep trying when I'm free tomorrow. I have appointments remainder of the day and an evening event too.

Thx for a killer app nonetheless.

**Comment by rom1v** [comment]
You requested to rotate to landscape, but the app refuses. This is expected for many camera apps.

The new feature in this PR consists in rotating the scrcpy window with `Ctrl`+`LEFT` and `Ctrl`+`RIGHT`.

**Comment by rom1v** [comment]
Fetaure merged in `dev`.

I also added `--rotation value` to set the initial rotation.

**Comment by perrette** [comment]
Excellent app and great feature !
For whoever ends here, it seems to have been changed to `ALT + LEFT` and `ALT + RIGHT` (scrcpy 2.3.1, Ubuntu 22.04).

**Comment by rom1v** [comment]
@perrette Yes, the default shortcuts modifier has been changed a long time ago (since v1.15 by #1598).

https://github.com/Genymobile/scrcpy/blob/master/doc/shortcuts.md

**Pull request closed without merging**
