### PR TITLE
Add shake shortcut to README

### PR DESCRIPTION
**Pull request by thomasvm**
As a react-native developer I was looking for a way trigger the shake gesture (to launch the development menu). Turns out it exists but was missing from the README. This pull request adds the shortcut to the shortcuts table

### CODE REVIEW

**Comment by rom1v** [comment]
This shortcut "Click on `MENU` (unlock screen)" (the fact that react-native binds `MENU` to "shake gesture" is a react-native detail).

t might be documented on the same line then:

> Click on `MENU` (unlock screen, shake gesture)

What do you think?

**Comment by rom1v** [comment]
Thank you.

I reordered the footnotes, and moves the reference to the shortcut description (instead of the shortcut keys): [`pr2879`](https://github.com/Genymobile/scrcpy/commits/pr2879`). Is it ok for you? https://github.com/Genymobile/scrcpy/commit/25a41359358a2032fdcc09482974d5fd15a06511

**Comment by thomasvm** [comment]
Perfect!

**Comment by rom1v** [comment]
:+1: merged.

**Pull request closed without merging**
