### PR TITLE
Add InputManagerGlobal method for Android 14 Beta3

### PR DESCRIPTION
**Pull request by DerekWuYD**
#4074
Add `InputManagerGlobal` method for Android 14 Beta3

Please skip the `ClibpoardManager.java` it same with `dev` branch.

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

I rebased on `dev` and simplified a bit: https://github.com/Genymobile/scrcpy/commits/pr4075

Please review and test (I have no device with Android 14).

**Comment by DerekWuYD** [comment]
Looks good, thank you. 👍

**Comment by rom1v** [comment]
Thank you.

FYI, `--turn-screen-off` is also broken on Android 14 (see #3784). If you have any solution to fix it, I'm interested :wink:

**Comment by DerekWuYD** [comment]
For issue #3784 is complex, so we need to wait until Android 14 source is available on AOSP.

**Comment by rom1v** [comment]
Merged into `dev`: 34adddcdae9cec008593f9b83fc36fdf9e46da61

**Comment by rom1v** [comment]
Oops, I made a mistake (I kept a wrong cast), so I edited the commit: 5bd75148716496755dc32daab21a322f51dc58ca and pushed-force `dev` branch.

Refs https://github.com/Genymobile/scrcpy/commit/03a8a71745e5cea6912be497f4188e99b765c702#r117821476

**Comment by Alaingent** [comment]
dear, could you please update scrcpy exe in order it is again "ok" to control my android Pixel 7a phone under Android 14 ? i don't really understand "above" explication, i m not technician. thank you.

**Comment by rom1v** [comment]
The latest version works for Android 14. Use the latest version (2.3.1).

**Comment by Alaingent** [comment]
Thank you it is now ok


Alain



Le ven. 15 déc. 2023, 19:56, Romain Vimont ***@***.***> a
écrit :

**Pull request closed without merging**
