### PR TITLE
Add --no-video (to mirror audio only)

### LINKED ISSUE #3842: Add an option to mirror audio only
- [x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I would like to share the audio of my device without the display window.

**Describe the solution you'd like**
Allow the `--no-display` argument without a record or v4l2 to receive only the audio of the device.

**Describe alternatives you've considered**
Add another command argument (like `--only-audio`) to transmit only the audio of the device.

### PR DESCRIPTION
**Pull request by rom1v**
As a first step, rename `--no-display` to `--no-mirror`:
 - the option impacts both video and audio playback, so "no display" is not an appropriate name
 - it is confusing with the option `--display=` which is totally unrelated (it refers to the device display)
 
Using the short version `-N` works as before.

Using `--no-display` still works, but generates a warning:

```
WARN: --no-display is deprecated, use --no-mirror instead.
```

Then add a new option `--no-video`:

```
scrcpy --no-video
```

And adapt recording to audio files:

```bash
scrcpy --no-video --record=file.opus
scrcpy --no-video --audio-codec=aac --record-file=file.aac
# .m4a/.mp4 and .mka/.mkv are also supported for both opus and aac
```

To record only:

```bash
scrcpy --no-mirror --record=file.opus
```

The `opus` muxer has been added to the prebuilt FFmpeg for windows releases: https://github.com/rom1v/scrcpy-deps/commits/6.0-scrcpy-3

Fixes #3842

---

Please review and test. Here is a release of this PR:

- [`scrcpy-win64-pr3978.zip`](https://tmp.rom1v.com/scrcpy/3978/2/scrcpy-win64-pr3978.zip) <sub>`SHA-256: 69c2eb1d3cad610a4e8488ffce6b8f66365b1375b321feb4f2426b3165a5c337`</sub>
- [`scrcpy-win32-pr3978.zip`](https://tmp.rom1v.com/scrcpy/3978/2/scrcpy-win32-pr3978.zip) <sub>`SHA-256: 559d582f04359ccf4ca72532e73b890079bd9276ba43946cc48d07571b1abc51`</sub>

### CODE REVIEW

**Comment by Piripe** [comment]
Just tried the `--no-video`, it works great.
I have no need to test other features of this PR, but if you want I can.

**Comment by rom1v** [comment]
@Piripe Thank you for your tests :+1:

If you could test recording only the audio to `.opus` and `.aac` and play it with some player (vlc, firefox, other…) to confirm that everything is ok, that would be great :)

**Comment by Piripe** [comment]
I tried recording only the audio with and without the mirroring, it works great!
<br><br>
I also made a little AHK script (I edited the script in the autoadb issues) using autoadb and scrcpy, I really like this way to mirror my phone 😀

https://github.com/Genymobile/scrcpy/assets/77517308/ce2980fc-0707-4432-98e1-9484954dabe3

(Note: I'm REALLY unorganized, as you can see in my taskbar)

The script:
```ahk
#NoTrayIcon
#Persistent

global hAutoadb

/* Setup Tray icon and add item that will handle
 * double click events
 */
Menu Tray, Icon
Menu Tray, Icon, icon.ico
Menu Tray, Add, Show / Hide autoadb, TrayClick
Menu Tray, Add, Mirror Display, DisplayClick
Menu Tray, Default, Mirror Display

;// Run autoadb hidden
DetectHiddenWindows On
Run autoadb scrcpy --no-video,, Hide, PID
WinWait ahk_pid %PID%
hAutoadb := WinExist()
DetectHiddenWindows Off
return

TrayClick:
OnTrayClick()
return

DisplayClick:
Run scrcpy --no-audio --turn-screen-off --stay-awake --show-touches -b 30M,,, PID
WinWait ahk_pid %PID%
hScrcpy := WinExist()
WinHide ahk_id %hScrcpy%
return

;// Show / hide Autoadb on double click
OnTrayClick() {
	if DllCall("IsWindowVisible", "Ptr", hAutoadb) {
		WinHide ahk_id %hAutoadb%
	
	} else {
		WinShow ahk_id %hAutoadb%
		WinActivate ahk_id %hAutoadb%
	}
}
```

**Comment by rom1v** [comment]
> Hi, will this work with v4l2? Currently, v4l2 with no display with --required-audio doesn't stream audio

I plan to add `--no-mirror-video` and `--no-mirror-audio` later (where `--no-mirror` would be an alias for both), so that you could use:

```
scrcpy --no-mirror-video --v4l2-sink=…
```

**Comment by rom1v** [comment]
Question about the option name: in this MR, `--no-display` has been renamed to `--no-mirror`.

I'm wondering if it should be called `--no-playback` instead (and `--no-video-playback`/`--no-audio-playback` for individual streams)?

For example, if we use a V4L2 think without a scrcpy window (`scrcpy --no-mirror --v4l2-sink=/dev/video2`), then we can consider we are still "mirroring" the device?

What do you think?

**Pull request merged**
