### PR TITLE
🇷🇺 Russian translation of README

### PR DESCRIPTION
**Pull request by jkulvich**
Thank you for your awesome tool!

Unfortunately, few Russian users know about this tool.
I hope that the translation of the README into Russian will help to make this tool more popular.

If you find translation inaccuracies or need to update Russian README with new documentation ASAP, please tag me.

### CODE REVIEW

**Comment by StupidRepo** [comment]
Just curious, what do you mean by `"Unfortunately, few Russian users know about this tool."`, how is this Unfortunate? Again, just curious and sorry if that sounded passive aggressive :)

**Comment by rom1v** [comment]
Hi,

Thank you for your translation.

I have a few requests. Could you please:
 - squash your commits (so that there is no "WIP:" commits")
 - remove the table of contents (it should be auto-generated, but until github support it, I prefer not to maintain tables manually, and other translations don't have it)
 - propose "flags emoji" separately for the main page (but not emojis everywhere like in the table of contents) (note: unfortunately, on my system, the flags don't appear in terminal, while others do)

Regards

> Just curious, what do you mean by "Unfortunately, few Russian users know about this tool.", how is this Unfortunate? 

I don't understand your remark.

**Comment by e1e0** [comment]
close? Translations in wiki.

**Comment by Aleksey-Voko** [comment]
What is wrong with this translation?
I would like to receive this translation.

**Comment by rom1v** [comment]
The translations are not in the repo itself anymore, they must be done in the wiki: https://github.com/Genymobile/scrcpy/wiki

Cf 72ba913324d65cded8672dca7a57415cb82da095

**Pull request closed without merging**
