### PR TITLE
Add clipboard workaround for Honor device

### PR DESCRIPTION
**Pull request by eiyooooo**
Similar to #3885, but newer version

```java
public ClipData getPrimaryClip(String pkg, String attributionTag, int userId, int deviceId, String stackTraceMsg)
```

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you.

Could you please post your framework.jar?

```
adb pull /system/framework/framework.jar
```

**Comment by eiyooooo** [comment]
> Could you please post your framework.jar?

[framework.zip](https://github.com/Genymobile/scrcpy/files/14896246/framework.zip)

**Comment by rom1v** [comment]
Thank you.

I refactored the current code base to avoid nested try-catch blocks (there are now too many cases for clipboard): d1a0f9b054fadde16b0d591d14f931b7b04d6656

Then I rebased your commit: ad8b824a283db1504a9ea031ed38bb167db48166

Does it look ok for you?

**Comment by eiyooooo** [comment]
> Does it look ok to you?

LGTM🫡

**Comment by rom1v** [comment]
Oops, sorry, I forgot this PR (and my branch `pr4822`), and re-implemented it :confused: 

https://github.com/Genymobile/scrcpy/issues/5073#issuecomment-2233173195

**Pull request closed without merging**
