### PR TITLE
Add `--no-kill-adb-before-hid` option

### PR DESCRIPTION
**Pull request by wh201906**
Hi. This is for https://github.com/Genymobile/scrcpy/issues/4028#issuecomment-1562390025
I'm not sure if the option name is good or not.

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you. I made some changes/fixes, and renamed hid to otg: branch [`no_kill_adb_before_otg`](https://github.com/Genymobile/scrcpy/commits/no_kill_adb_before_otg).

However, after thinking about it, I think this option is useless. In #4032, you say:

> To monitor the phone and control it at the same time, I need to use adb over TCP and keyboard simulation in OTG mode.
However, If I start scrcpy for monitoring first and start another instance in otg mode for keyboard simulation, the latter will kill the adb daemon. So I have to start the scrcpy in otg mode first, then start scrcpy for monitoring.
> […]
> To start the two instances mentioned above in any sequence, I'd like to add an option to prevent killing adb daemon in otg mode

If you start the adb daemon first, and don't kill it, your device will not be detected in otg mode, so `scrcpy --otg` will fail. That's the reason why it kills adb (to make it work). So this new option will not help.

**Comment by wh201906** [comment]
You mean the scrcpy still uses adb to detect the Android device even with the `--otg`, right?

**Comment by yume-chan** [comment]
Maybe Scrcpy can call `adb -s <serial> detach` or `adb -t <transport-id> detach` to let ADB server release the USB device, so it doesn't need to kill the ADB server.

**Comment by rom1v** [comment]
> You mean the scrcpy still uses adb to detect the Android device even with the `--otg` option, right?

No, but if the USB device is open by adb, then scrcpy will not be able to open it separately for OTG. On other OS, it is perfectly ok to open a USB device already open by another program, but not on Windows.

@yume-chan maybe, to be tested. 😃

**Comment by wh201906** [comment]
> 

How about the adb over TCP? I know it's impossible to use mirroring and otg on the same phone via USB, but I can use mirroring over TCP and otg over USB

**Comment by rom1v** [comment]
> Do you mean the device becomes undetectable if it is connected by adb, even via TCP?

By default, if you plug the device and USB debugging is enabled, the adb daemon will detect it and open it, even if you don't use it.

**Comment by wh201906** [comment]
> By default, IIRC, if you plug the device and USB debugging is enabled, the adb daemon will detect it and open it, even if you don't use it.

If so, this option is useless indeed. Thank you for checking this.
Should I close this pull request now?

**Comment by yume-chan** [comment]
Tried the `adb detach` command. First it outputs:

```
> adb detach
adb.exe: failed to detach: attach/detach only implemented for libusb backend
NativeCommandExitException: Program "adb.exe" ended with non-zero exit code: 1.
```

Launch adb with libusb backend:

```
> $env:ADB_LIBUSB="1"
> adb server nodaemon
adb.exe F 06-02 21:49:59 14088 15940 usb_libusb.cpp:972] failed to register libusb hotplug callback
NativeCommandExitException: Program "adb.exe" ended with non-zero exit code: -1073740791.
```

it crashes immediately (due to unknow error, not the error it logged).

**Pull request closed without merging**
