### PR TITLE
Fix touch events for LG devices

### PR DESCRIPTION
**Pull request by DerekJedral**
Haven't had the ability to test on other devices, but this solves the touch events issue on my V20

### CODE REVIEW

**Comment by rom1v** [comment]
Wow, cool it the problem is fixed with it! :+1:

I will test on other devices before merging.

**Comment by rom1v** [comment]
Could you add a comment in code to say that 1 does not work for LG devices and add a link to https://github.com/Genymobile/scrcpy/issues/18, please?

**Comment by rom1v** [comment]
I'm wondering, what if instead you remove these lines:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/EventController.java b/server/src/main/java/com/genymobile/scrcpy/EventController.java
index 4a0ce33..547e20c 100644
--- a/server/src/main/java/com/genymobile/scrcpy/EventController.java
+++ b/server/src/main/java/com/genymobile/scrcpy/EventController.java
@@ -39,10 +39,6 @@ public class EventController {
         coords.orientation = 0;
         coords.pressure = 1;
         coords.size = 1;
-        coords.toolMajor = 1;
-        coords.toolMinor = 1;
-        coords.touchMajor = 1;
-        coords.touchMinor = 1;
     }
 
     private void setPointerCoords(Point point) {
```

Does it work for LG devices?

**Comment by Cascador** [comment]
Works too.

Tcho !

**Comment by rom1v** [comment]
OK, then I fixed it that way (it seems less hacky): https://github.com/Genymobile/scrcpy/commit/c075ad0a1e9e496bd2b0adf353d539933aa8c7ee

Thank you all.

**Pull request closed without merging**
