### PR TITLE
Add manpage for scrcpy

### PR DESCRIPTION
**Pull request by yangfl**
I don't know if I put the file in the right directory, if not please tell me.

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

I suggest the following changes:

```diff
diff --git a/app/scrcpy.1 b/app/scrcpy.1
index ddf2649..fda53e5 100644
--- a/app/scrcpy.1
+++ b/app/scrcpy.1
@@ -10,7 +10,7 @@ scrcpy \- Display and control your Android device
 
 .SH DESCRIPTION
 .B scrcpy
-provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access. It works on GNU/Linux, Windows and MacOS.
+provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.
 
 
 .SH OPTIONS
@@ -34,7 +34,7 @@ value is computed on the cropped size.
 Start in fullscreen.
 
 .TP
-.B \-F, \-\-record\-format
+.BI "\-F, \-\-record\-format " format
 Force recording format (either mp4 or mkv).
 
 .TP
@@ -68,7 +68,7 @@ Set the target directory for pushing files to the device by drag & drop. It is p
 Default is "/sdcard/".
 
 .TP
-.BI "\-r, \-\-record " file.mp4
+.BI "\-r, \-\-record " file
 Record screen to file.
 
 The format is determined by the
@@ -106,7 +106,7 @@ Print the version of scrcpy.
 Set a custom window title.
 
 
-.SH Shortcuts
+.SH SHORTCUTS
 
 .TP
 .B Ctrl+f
@@ -196,16 +196,23 @@ Specify the path to adb.
 Specify the path to server binary.
 
 
-.SH AUTHOR
+.SH AUTHORS
 .B scrcpy
-is written by
-.UR https://www.genymobile.com
-Genymobile
-.UE
-and Romain Vimont.
-
-This manual page was written by
-.MT mmyangfl@\:gmail.com
-Yangfl
-.ME
-for the Debian Project (and may be used by others).
+is written by Romain Vimont.
+
+This manual page was written by Yangfl <mmyangfl@gmail.com> for the Debian
+Project (and may be used by others).
+
+
+.SH "REPORTING BUGS"
+Report bugs to <https://github.com/Genymobile/scrcpy/issues>.
+
+.SH COPYRIGHT
+Copyright \(co 2018 Genymobile <https://www.genymobile.com>
+.br
+Copyright \(co 2018\-2019 Romain Vimont <rom@rom1v.com>
+
+Licensed under the Apache License, Version 2.0.
+
+.SH WWW
+<https://github.com/Genymobile/scrcpy>
```

Is it ok for you?

**Comment by yangfl** [comment]
Fine, but what's wrong with MT/ME and UR/UE macros?

**Comment by rom1v** [comment]
> what's wrong with MT/ME and UR/UE macros?

The main reason is that they use `()` instead of `<>` for URLs. But if it's better (I have no experience in writing manpages), I can use them:

```diff
diff --git a/app/scrcpy.1 b/app/scrcpy.1
index fda53e5..34b8168 100644
--- a/app/scrcpy.1
+++ b/app/scrcpy.1
@@ -200,19 +200,31 @@ Specify the path to server binary.
 .B scrcpy
 is written by Romain Vimont.
 
-This manual page was written by Yangfl <mmyangfl@gmail.com> for the Debian
-Project (and may be used by others).
+This manual page was written by
+.MT mmyangfl@gmail.com
+Yangfl
+.ME
+for the Debian Project (and may be used by others).
 
 
 .SH "REPORTING BUGS"
-Report bugs to <https://github.com/Genymobile/scrcpy/issues>.
+Report bugs to
+.UR https://github.com/Genymobile/scrcpy/issues
+.UE
 
 .SH COPYRIGHT
-Copyright \(co 2018 Genymobile <https://www.genymobile.com>
+Copyright \(co 2018 Genymobile
+.UR https://www.genymobile.com
+Genymobile
+.UE
 .br
-Copyright \(co 2018\-2019 Romain Vimont <rom@rom1v.com>
+Copyright \(co 2018\-2019
+.MT rom@rom1v.com
+Romain Vimont
+.ME
 
 Licensed under the Apache License, Version 2.0.
 
 .SH WWW
-<https://github.com/Genymobile/scrcpy>
+.UR https://github.com/Genymobile/scrcpy
+.UE
```

What do you think?

Btw, how to add a `.` at the end of `Report bugs to (https://github.com/Genymobile/scrcpy/issues)`?  In the source file, it would need to appear alone on the line, but I can't fine a way to make it work (`.`, `(space).`, `\.`…)

**Comment by yangfl** [comment]
> The main reason is that they use `()` instead of `<>` for URLs.

On my system (Debian) `<>` are also used for URLs. And a strong reason to use macros is they help rendering better pages in other formats, like HTML. (see linux.die.net)

> Btw, how to add a `.` at the end of `Report bugs to (https://github.com/Genymobile/scrcpy/issues)`? In the source file, it would need to appear alone on the line, but I can't fine a way to make it work (`.`, `(space).`, `\.`…)

`.UE .`
`.ME .`

**Pull request merged**
