### PR TITLE
Customize shortcut modifier and forward Ctrl and Shift to the device

### LINKED ISSUE #555: support passing in Home and Ctrl-x keys
When I press the `End` key, my cursor jumps to the end of line. But when I press the `Home` key, it returns to the home screen instead of jumping to the start of line.

Key combinations like Ctrl-sth don't work either.

I suggest adding an option to enable all of this, and make scrcpy-specific keys prefixed by a certain key (e.g. the host key in Virtualbox, or the prefix key in screen / tmux).

Even better, can you emulate the keyboard as a physical keyboard (like physically connected to the phone).

This kind of improvements will make typing in scrcpy easiler because the user will not need to switch between mouse and keyboard that often.

### PR DESCRIPTION
**Pull request by rom1v**
This PR replace the two previous attempts #1446 and #1465.

It forwards <kbd>Ctrl</kbd> and <kbd>Shift</kbd> to the device. This allows for example to press <kbd>Ctrl</kbd>+<kbd>t</kbd> in Firefox to open a new tab, <kbd>Ctrl</kbd>+<kbd>w</kbd> to close the current tab. <kbd>Ctrl</kbd>+<kbd>c</kbd> or <kbd>Ctrl</kbd>+<kbd>d</kbd> can now be injected in Termux.

This also greatly simplifies text selection, by using the keyboard (<kbd>Shift</kbd>+_arrows_, <kbd>Ctrl</kbd>+<kbd>a</kbd>…), and simplify copy-paste (<kbd>Ctrl</kbd>+<kbd>c</kbd>) and cut-paste (<kbd>Ctrl</kbd>+<kbd>x</kbd>). <kbd>Ctrl</kbd>+<kbd>z</kbd> could be use to cancel an action, like a change in a text field for example.

As a consequence, scrcpy shortcuts are not bound to <kbd>Ctrl</kbd> anymore, but to (left) <kbd>Alt</kbd> and (left) <kbd>Cmd</kbd> by default. This modifier can be changed by a command-line parameter (`--shortcut-mod`), as explained [here](https://github.com/Genymobile/scrcpy/pull/1465#issuecomment-656388080).

Here is the list of the changes:
 - all shortcuts now use the specified modifier key (called <kbd>MOD</kbd>), on all platforms
 - <kbd>Ctrl</kbd> and <kbd>Shift</kbd> are forwarded to the device
 - to copy or cut a text, <kbd>Ctrl</kbd>+<kbd>c</kbd> and <kbd>Ctrl</kbd>+<kbd>x</kbd> typically work, because they are forwarded to the device, which, in a text field, copy the text into the clipboard… and the clipboard is now automatically (since v1.13) synchronized with the computer keyboard
 - pressing <kbd>Ctrl</kbd>+<kbd>v</kbd> synchronizes the computer clipboard to the device before sending the key event, therefore pasting typically works seamlessly
 - seamless copy-paste now also works before Android 7 with `Ctrl` keys
 - <kbd>MOD</kbd>+<kbd>c</kbd>, <kbd>MOD</kbd>+<kbd>x</kbd> and <kbd>MOD</kbd>+<kbd>v</kbd> are also provided to inject `COPY`, `CUT` and `PASTE` keycodes (see [README](https://github.com/Genymobile/scrcpy/blob/163eb4ba5e95f0ae590b65532267d75f2827965b/README.md#copy-paste) for details)
 - <kbd>MOD</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd> injects the computer clipboard content as a sequence of key events (this is still useful sometimes)
 - to be able bind `CUT` to <kbd>MOD</kbd>+<kbd>x</kbd>, the "resize to fit" shortcut (which removes the black borders) has been changed to <kbd>MOD</kbd>+<kbd>w</kbd>

This fixes #555 and #942.

Feedbacks (and reviews) welcome :)

## Binaries

For windows users, take both `scrcpy.exe` and `scrcpy-server`, and replace them in your scrcpy v1.14 release.

For other platforms, take `scrcpy-server` and [build](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#prebuilt-server) only the client.

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/1598/2/scrcpy.exe)
  _SHA256: ceab026bff28c8851456e30d3e1449ad25ef6aedeec6fcac00ad508e2f67a9cf_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/1598/2/scrcpy-server)
  _SHA256: b7b4f2f5d008cf6191c8fab6f74cc43bfc78bd33c4a4100274a9f4fa717b59e8_

### CODE REVIEW

**Comment by rom1v** [comment]
Oh, when pressing <kbd>Alt</kbd>+<kbd>c</kbd>, SDL generates a text event (`SDL_TextInputEvent`) containing `c`.

As a consequence, when `--prefer-text` is passed, a `c` is inserted on such a shortcut :confused:

**Comment by lsdy0806** [comment]
Hello, under the default ALT shortcut, ALT+W has no effect on removing black borders.

**Comment by brunoais** [comment]
@Helaer It works fine for me on a PT-PT keyboard. What's your keyboard layout?

@rom1v Works awesome to me. After some use, I settled with `--shortcut-mod="ralt"` for me (`AltGr`). It's much easier and faster to stick out the thumb without that much deflection. I do understand well that there are keyboards without such key. Being able to choose is great.
I tried around to use app shortcuts and they worked well as expected. 15 mins using the phone with shortcuts and such didn't show any signs of issues or bugs for me. Including using `AltGr+W` to resize the window.

**Comment by Helaer** [comment]
> @Helaer在PT-PT键盘上对我来说效果很好。您的键盘布局是什么？
> 
> @ rom1v对我来说很棒。使用一段时间后，我`--shortcut-mod="ralt"`为我定居了（`AltGr`）。伸出拇指而没有那么大的挠曲会更加轻松快捷。我非常了解有些键盘没有这样的键。能够选择很棒。
> 我尝试使用应用程序快捷方式，它们按预期运行良好。15分钟使用带有多个`Ctrl`快捷方式的电话，这对我来说没有任何问题或错误的迹象。包括`AltGr+W`用于调整窗口大小。
> 顺便说一句，在我的Linux系统中，我使用源代码进行了完整构建，而不是使用您的预构建服务器。出于某种原因，我收到了`segmentation fault`，但无法快速修复。
> 所以我做了一个完整的构建。

I didn't pass in a set of bytes, the default shortcut used, ALT+W can not remove the black border of the window.

**Comment by rom1v** [comment]
@Helaer 

> Hello, under the default ALT shortcut, ALT+W has no effect on removing black borders.

Which platform/window manager? On Debian+XFCE, <kbd>Alt</kbd>+<kbd>w</kbd> works fine.
What about <kbd>Cmd</kbd>+<kbd>w</kbd> on your computer (<kbd>Cmd</kbd> is the <kbd>Windows</kbd> key on some keyboards)?

@brunoais  Thank you for your feedbacks :+1: 

> After some use, I settled with `--shortcut-mod="ralt"` for me (`AltGr`).

On a French keyboard, <kbd>AltGr</kbd> is used to generate many chars (<kbd>AltGr</kbd>+<kbd>0</kbd> is `@`, <kbd>AltGr</kbd>+<kbd>6</kbd> is `|`, and many many others).

> I did a full build with the source code instead of taking your prebuilt server. For some reason, I was getting a `segmentation fault` and I was unable to fix it quick. 

Oh, a segmentation fault on the client side or device side? (does it appear in `adb logcat`)
Can you reproduce?

Add `-Db_sanitize=address` to your meson command, and retry. It will give more details if it's on the client side.
For example, you can update your meson configuration and rebuild:

```bash
meson configure x -Db_sanitize
ninja -Cx
./run x
```

**Comment by Helaer** [comment]
> @海拉尔
> 
> > 您好，在默认的ALT快捷方式下，ALT + W对删除黑色边框无效。
> 
> 哪个平台/窗口管理器？在Debian + XFCE上，Alt+ w可以正常工作。
> 什么Cmd+ w您的计算机上（Cmd是Windows某些键盘上的键）？
> 
> @brunoais 谢谢您的反馈👍
> 
> > 使用一段时间后，我`--shortcut-mod="ralt"`为我定居了（`AltGr`）。
> 
> 在法语键盘上，AltGr用于生成许多字符（AltGr+ 0是`@`，AltGr+ 6是`|`，以及许多其他字符）。
> 
> > 我使用源代码进行了完整构建，而不是使用您的预构建服务器。出于某种原因，我收到了`segmentation fault`，但无法快速修复。
> 
> 哦，客户端或设备端的分段错误？（出现在中`adb logcat`）
> 您可以复制吗？
> 
> 添加`-Db_sanitize=address`到您的介子命令，然后重试。如果是在客户端，它将提供更多详细信息。
> 例如，您可以更新介子配置并重建：
> 
> ```shell
> 介子配置x -Db_sanitize
> 忍者-Cx
> ./运行x
> ```

My system is Windows 10.

**Comment by rom1v** [comment]
I just tested on Windows 10: I resized the scrcpy window so that there are black borders, then I pressed <kbd>Alt</kbd>+<kbd>w</kbd>, it works for me, the window is automatically resized so that black borders are gone.

**Comment by Helaer** [comment]
> 我刚刚在Windows 10上进行了测试：我调整了scrcpy窗口的大小以使其具有黑色边框，然后按Alt+ w，它对我有用，该窗口会自动调整大小以使黑色边框消失。

I restarted my computer and it responded, guessing that other applications blocked the key combination.

**Comment by brunoais** [comment]
> @Helaer
> 
> > Hello, under the default ALT shortcut, ALT+W has no effect on removing black borders.
> 
> Which platform/window manager? On Debian+XFCE, Alt+w works fine.
> What about Cmd+w on your computer (Cmd is the Windows key on some keyboards)?
> 
> @brunoais Thank you for your feedbacks +1
> 
> > After some use, I settled with `--shortcut-mod="ralt"` for me (`AltGr`).
> 
> On a French keyboard, AltGr is used to generate many chars (AltGr+0 is `@`, AltGr+6 is `|`, and many many others).
> 
> > I did a full build with the source code instead of taking your prebuilt server. For some reason, I was getting a `segmentation fault` and I was unable to fix it quick.
> 
> Oh, a segmentation fault on the client side or device side? (does it appear in `adb logcat`)
> Can you reproduce?
> 
> Add `-Db_sanitize=address` to your meson command, and retry. It will give more details if it's on the client side.
> For example, you can update your meson configuration and rebuild:
> 
> ```shell
> meson configure x -Db_sanitize
> ninja -Cx
> ./run x
> ```



> @Helaer
> 
> > Hello, under the default ALT shortcut, ALT+W has no effect on removing black borders.
> 
> Which platform/window manager? On Debian+XFCE, Alt+w works fine.
> What about Cmd+w on your computer (Cmd is the Windows key on some keyboards)?
> 
> @brunoais Thank you for your feedbacks +1
> 
> > After some use, I settled with `--shortcut-mod="ralt"` for me (`AltGr`).
> 
> On a French keyboard, AltGr is used to generate many chars (AltGr+0 is `@`, AltGr+6 is `|`, and many many others).

I have such too. Except it never worked in scrcpy. I end up using the phone's virtual keyboard for those characters.
When that's solved, then I may change the combination to `--shortcut-mod="ralt+rctrl"`, for example.
The phone is running  Android `6.0.0`

> Oh, a segmentation fault on the client side or device side? (does it appear in `adb logcat`)

I'm not sure, I can only see a connection lost on logcat. No process dump or stack trace.

> Can you reproduce?

When I 

> Add `-Db_sanitize=address` to your meson command, and retry. It will give more details if it's on the client side.
> For example, you can update your meson configuration and rebuild:
> 
> ```shell
> meson configure x -Db_sanitize
> ninja -Cx
> ./run x
> ```

When I do it like that, everything runs right. I think ninja is recompiling when I run it like that. So I think I would need to run it in some different way so it uses the server you uploaded there while using the client code from my side.

Regardless, if I checkout `cdd6f186`, optionally run `meson` and then run `ninja`, all runs fine and smoothly. :+1:

**Comment by rom1v** [comment]
> I have such too. Except it never worked in scrcpy. I end up using the phone's virtual keyboard for those characters.

Even with `scrcpy --prefer-text`?

> When I do it like that, everything runs right.

What about:

```bash
meson configure x -Dprebuilt_server=/path/to/your/prebuilt/scrcpy-server
...
```
?

**Comment by brunoais** [comment]
> > I have such too. Except it never worked in scrcpy. I end up using the phone's virtual keyboard for those characters.
> 
> Even with `scrcpy --prefer-text`?
> 
> > When I do it like that, everything runs right.
> 
> What about:
> 
> ```shell
> meson configure x -Dprebuilt_server=/path/to/your/prebuilt/scrcpy-server
> ...
> ```
> 
> ?



> > I have such too. Except it never worked in scrcpy. I end up using the phone's virtual keyboard for those characters.
> 
> Even with `scrcpy --prefer-text`?
> 
> > When I do it like that, everything runs right.

Yeah... It does... However, I still will lose the ability with other programs that are listening to keys (you exemplify games)

> 
> What about:
> 
> ```shell
> meson configure x -Dprebuilt_server=/path/to/your/prebuilt/scrcpy-server
> ...
> ```
> 
> ?

I didn't know that option existed I'll try that tomorrow.

**Comment by brunoais** [comment]
> > What about:
> > ```shell
> > meson configure x -Dprebuilt_server=/path/to/your/prebuilt/scrcpy-server
> > ...
> > ```
> > 
> > 
> > ?
> 
> I didn't know that option existed I'll try that tomorrow.

No crash if I do like that.

**Comment by AzureRaptor** [comment]
@rom1v Just want to mention that on my platform, Windows 10, Samsung Galaxy S5, the two most recent binaries are working perfectly.  Have tested passing ctrl keys for bash in termux, and everything I've thought of has been flawless.  I'm using the "hacker's keyboard" keyboard replacement app also, if that matters.  Also tested scrcpy builtins for turn off screen, pull menushade, switch programs, etc.  All working fine.

Thank you _so, so_ much for this.  This is saving me a ton of pain futzing with the soft keyboard in termux.

**Comment by rom1v** [comment]
@AzureRaptor Thank you very much for your feedbacks. It's very helpful :+1:

**Comment by AzureRaptor** [comment]
I have noticed something else that is a bit odd, although not insurmountable thus far.

Somehow, after an indeterminate period of time (it seems to take more than half an hour - I _think_ - I'm sorry I haven't timed this better) scrcpy seems to get into a state where the middle mouse-button  no longer works for "home."  If I click it, nothing happens.  I've given it over a minute to respond during times when the phone is not being used or cpu-stressed.

If I just close and restart scrcpy the behavior stops and middle button works again.

**Comment by rom1v** [comment]
Except HOME, everything continued workibg (left-clock, BACK...)?

Did you reproduce it several times?

**Comment by AzureRaptor** [comment]
Yes, that's pretty much exactly what I observed.  Middle-button failure for HOME was the only unexpected result.

I've observed it at least three times now.

**Comment by rom1v** [comment]
If you reproduce it again, could you test whether Ctrl+h (for HOME) still works when middle-clic fails, please?

**Comment by rom1v** [comment]
Also, can you reproduce it on a version which do not include the changes from this PR?

**Comment by AzureRaptor** [comment]
> If you reproduce it again, could you test whether Ctrl+h (for HOME) still works when middle-clic fails, please?

Ok.  Have just tested the build from this PR, and ALT-H (which is what I expect for this build, right?) works for home.  This is good.

I'll try to test a report on the last stable as soon as I can.  I'm glad I kept those binaries around and renamed them.  It's basically going to involve me digging out some idle time and letting the phone sit and wait, because I really need the keyboard functionality this build to work sanely at all.  🤣

**Comment by AzureRaptor** [comment]
I have an update.  Still haven't tested out the older binaries yet, sorry, but just a little while ago this pull got into a state where _both_ middle-click and alt-h did not respond.  I'm afraid I closed it before I tested other inputs (was in the middle of working and it was stopping me 😒).  Next time this happens, I'll try to see what else is responding at the time.  Hopefully this was maybe a one-off fluke.

**Comment by rom1v** [comment]
> where both middle-click and alt-h did not respond.

When you reproduce, could you also test `adb shell input keyevent HOME`?
If that works, does it make right-click / Alt+h work again?

Are there any errors in `adb logcat`?

**Comment by AzureRaptor** [comment]
Ok.  I've been able to catch the trouble state again, and can report `adb shell input keyevent HOME` does indeed behave as a home keypress or middle-click (I'm sure that's what you meant, not right-click?) were pressed.  The condition of ignoring those events persisted, however.

As far as `adb logcat` goes, that produced an _astonishing_ volume of output.  I'm afraid I'm not familiar enough with Android to know what I'm looking for in there.  All I could think to do was hit middle-click and alt+h several times, then `adb logcat | find /i "error"`, and look over the past minute's worth of errors and see if anything obviously jumped out at me.  I saw nothing that looked like scrcpy could have generated it, or anything that looked like an input, touch, or keypress error.  If you can tell me what I should look for, the next time I get into the trouble state, I'll try to give a better report.

**Comment by rom1v** [comment]
> The condition of ignoring those events persisted, however.

But only these ones. Pressing left-click or right-click, or even Alt+p (power) or Alt+b (back), or other key events, continue to work?

For `adb logcat`:

```bash
adb logcat -c  # clear logs
scrcpy
# when HOME fails, dump the logs
adb logcat -d > logcat.txt
```

Then post the file.

**Comment by brunoais** [comment]
Is it possible to add SUPER key (windows/linux key) to the possible options for `shortcut-mod`?

**Comment by rom1v** [comment]
SUPER is `lcmd`. Should I rename `cmd` to `super`?

**Comment by brunoais** [comment]
I'd have both as synonyms because `cmd` is a Mac thing and that's how Mac users are used to call it while `super` is the actual key's name.
I'm fine if it's just a rename, though.

**Comment by rom1v** [comment]
Ideally, I would like to avoid aliases to avoid confusion.

In SDL, it's called GUI: https://wiki.libsdl.org/SDL_Keymod

So maybe `lgui` and `rgui`?

**Comment by brunoais** [comment]
I think that's worse.
In that case, I'd just mention they are the same in the instructions (README file)

**Comment by Helaer** [comment]
After using it for a period of time, there is no problem of invalidation of the shortcut keys, which is great!

**Comment by rom1v** [comment]
I will probably rename `lcmd` and `rcmd` to `lsuper` and `rsuper`: https://en.wikipedia.org/wiki/Super_key_(keyboard_button)

**Comment by brunoais** [comment]
I think that should be the best course of action but maybe with parenthesis telling it's the cmd key in Mac.

**Comment by rom1v** [comment]
I replaced "cmd" by "super" and merged :tada:

**Comment by KeronCyst** [comment]
Sweet! Just to be clear, is this going to make its way into v1.15 or will we always have to replace the executables per release?

**Comment by rom1v** [comment]
Will be in v1.15.

https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#branches

**Comment by KeronCyst** [comment]
Great, but now I'm noticing that it seems to screw up **scrcpy-noconsole.exe** when I do this (any keyboard tap of anything disables all computer input).

**Comment by rom1v** [comment]
You need to build `scrcpy-noconsole.exe` from that version (`dev`), you can't use the one from v1.14.

**Comment by KeronCyst** [comment]
Gotcha. Now that I've tried it, `mod` doesn't recognize Right Alt, but it'd be very nice if it could do both.

**Comment by rom1v** [comment]
@KeronCyst `scrcpy --shortcut-mod=lalt,ralt`?

**Comment by KeronCyst** [comment]
Oh! I didn't know that could be done! Cool!

**Comment by rom1v** [comment]
I didn't enable right-Alt by defauly because it is sometimes AltGr, which is used for many characters.

**Comment by AzureRaptor** [comment]
@rom1v I noticed you'd added some commits and merged a couple of days ago.  Are the binaries and checksums linked in the first post still valid, or are there others somewhere?  I'm guessing not, but I don't know how to find them.  I apologize in advance if this is something very basic to github I should be able to tell from the posts.  😟

**Comment by rom1v** [comment]
No, there are no binaries for the current `dev` branch. I will release v1.15 soon (hopefully this week), which will include these changes.

**Comment by AzureRaptor** [comment]
I have some good news and bad news.  😅 

On the plus side, I have a logcat file for you.  I also can still confirm that all other keystrokes/mouseclicks seem to be working fine.  I even enabled both left & right alt as per your cmdline suggestion above; having both works better for me.

On the less-than-plus side, even though I definitely cleared the log as per your instructions further above, the problem didn't show up until I'd been working for several hours.  The logcat file is ~3M.  I doubt that would paste well here, and it's waaay above even the max size on pastebin.  I'm not sure how to get it to you or make it available.  I'm open to suggestions.

Thank you very much for your ongoing patience and work on this.

**Comment by rom1v** [comment]
> the problem didn't show up until I'd been working for several hours.

OK, thank you for the feedback. :+1:

I think that the middle-click issue you observe is not related to this PR anyway (and maybe not to scrcpy at all, I can't see a reason why only this key would stop working, you should check whether SDL still receives the event when it fails, by adding a log).

**Comment by rom1v** [comment]
> I think that the middle-click issue you observe is not related to this PR anyway

@AzureRaptor So I was totally wrong, I failed to find it before the release :disappointed: 
So now it is fixed in v1.15.1 :D (see #1643).

**Comment by AzureRaptor** [comment]
> @AzureRaptor So I was totally wrong, I failed to find the issue before the release 😞

Please don't feel bad about this.  I'm really sorry I was never able to get you a good logcat, but they just got _huge_ before the problem ever showed up and I couldn't figure out a good way to make them public (aside from something like dropbox or gdrive, which would've been a different kind of irritating).

I really find scrcpy indispensable.  I wish I had the cash to support your development; the work you're putting in is amazing.

**Comment by elvisisvan** [comment]
i'm on windows 10 scrcpy 2.3.1 (installed using winget) and the current default mod keys are **LSuper** and **LAlt** is there a way to remove LAlt as mod key? (i want to switch application using `alt+tab` but instead the focus returns to laptop)

i have tried using `--shortcut-mod` flag to specifically set only LSuper as mod key but did not work...
`scrcpy --otg -s 26021JEGR17923 --shortcut-mod="lsuper"`
image
what am i missing here?

**Comment by rom1v** [comment]
>(i want to switch application using alt+tab but instead the focus returns to laptop)

This is captured by your system so scrcpynis notnzven aware that you press alt+tab.

**Comment by rom1v** [comment]
Anyway, in OTG mode there are no scrcpy shortcuts.

**Comment by elvisisvan** [comment]
> > (i want to switch application using alt+tab but instead the focus returns to laptop)
> 
> This is captured by your system so scrcpy is not even aware that you press alt+tab.

if scrcpy is not aware of the `alt+tab` action why does the mouse and keyboard focus back to laptop?

**Comment by rom1v** [comment]
It captures Alt, but if you press Tab in addition, it is captured by the system.

**Comment by elvisisvan** [comment]
> Anyway, in OTG mode there are no scrcpy shortcuts.

in otg mode when i press either Super or left Alt key the focus moves back to laptop, how can i make it so only when i press Super key  the focus will change, not the any other key?

**Comment by rom1v** [comment]
The mouse capture keys are hardcoded:
https://github.com/Genymobile/scrcpy/blob/7f23ff3f2ca64dae6eb8b0ca9a881230184ae756/app/src/usb/screen_otg.c#L139-L142

**Comment by elvisisvan** [comment]
> The mouse capture keys are hardcoded:
> 
> https://github.com/Genymobile/scrcpy/blob/7f23ff3f2ca64dae6eb8b0ca9a881230184ae756/app/src/usb/screen_otg.c#L139-L142

what was the last version which it was not hardcoded? why did you hardcode both super key and left alt key, not just super key?

**Comment by rom1v** [comment]
> what was the last version which it was not hardcoded?

It is hardcoded since the beginning: 91418c79ab3b7056c21ef6c64f903704c8f00a52

> why did you hardcode both super key and left alt key, why not just super key?

Because different OS and desktop environments (and virtual machines) capture different keys, so I wanted a working solution for all cases.

**Comment by elvisisvan** [comment]
> > what was the last version which it was not hardcoded?
> 
> It is hardcoded since the beginning: [91418c7](https://github.com/Genymobile/scrcpy/commit/91418c79ab3b7056c21ef6c64f903704c8f00a52)
> 
> > why did you hardcode both super key and left alt key, why not just super key?
> 
> Because different OS and desktop environments (and virtual machines) capture different keys, so I wanted a working solution for all cases.

since you hardcoded those 2 keys since the beginning when otg mode feature was created there's no version of scrcpy i can revert back to achieve what i want, which left me with a remaining option is to find a way to configure my specific environment so it will only capture **Super** key, would that be possible now?

**Comment by rom1v** [comment]
> since you hardcoded those 2 keys since the beginning when otg mode feature was created there's no version of scrcpy i can revert back to achieve what i want

This is open source. Clone the project, change the line to adapt, rebuild :wink:

**Pull request merged**
