### PR TITLE
add debian package files

### PR DESCRIPTION
**Pull request by shouhuanxiaoji**
add an directory to build scrcpy to debian package.I saw that @yangfl has been contributed one in https://salsa.debian.org/yangfl-guest/scrcpy,so I update the version 1.4 to 1.6 and a little refinement was made.

you can directly clone the repo, and make the bash

`dpkg-buildpackage -us -uc -b -tc`

to make a debian package.

### CODE REVIEW

**Comment by Biswa96** [comment]
Why? Debian package files should be in Debian repository only. There are thousands GNU/Linux distribution, should all they be here?

**Comment by shouhuanxiaoji** [comment]
I saw that scrcpy has offer .exe packages for windows user.and .deb is the most popular package format for linux user.so I think we should offer an linux version.

**Comment by yangfl** [comment]
There's no need to add debian/ files upstream, as those files won't be admitted by Debian.

**Comment by rom1v** [comment]
@yangfl scrcpy is still v1.14 in Debian unstable.

Do you think you'll find some time to update to v1.17 before Bullseye freeze (before January 12th I guess)? https://release.debian.org/bullseye/freeze_policy.html

Thank you

**Comment by yangfl** [comment]
Well the build-dep android-sdk-meta is buggy so we will almost surely miss this release :/

**Comment by rom1v** [comment]
> Well the build-dep android-sdk-meta is buggy

What's the problem?

If I just execute this, it seems to work:

```
$ sudo apt build-dep android-sdk-meta
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dh-exec
0 upgraded, 1 newly installed, 0 to remove and 137 not upgraded.
Need to get 26.6 kB of archives.
After this operation, 141 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.fr.debian.org/debian testing/main amd64 dh-exec amd64 0.23.2 [26.6 kB]
Fetched 26.6 kB in 0s (466 kB/s)  
Selecting previously unselected package dh-exec.
(Reading database ... 640148 files and directories currently installed.)
Preparing to unpack .../dh-exec_0.23.2_amd64.deb ...
Unpacking dh-exec (0.23.2) ...
Setting up dh-exec (0.23.2) ...
Processing triggers for man-db (2.9.3-2) ...
Scanning processes...                                                           
Scanning candidates...                                                                                                                          
Scanning processor microcode...                                                                                                                 
Scanning linux images...
The processor microcode seems to be up-to-date.
Restarting services...
...
```

**Comment by yangfl** [comment]
That is android-sdk-meta can't make its way into testing (for some reasons), thus we cannot enter testing too, nah.

**Comment by rom1v** [comment]
Oh ok :cry: 

Indeed, scrcpy has been removed from testing:
https://tracker.debian.org/pkg/scrcpy
https://tracker.debian.org/pkg/android-sdk-meta

:disappointed:

**Comment by rom1v** [comment]
@yangfl Some news yesterday for [android-sdk-meta](https://tracker.debian.org/pkg/android-sdk-meta): https://tracker.debian.org/news/1220678/accepted-android-sdk-meta-28021-source-into-unstable/

**Comment by rom1v** [comment]
https://tracker.debian.org/pkg/android-sdk-meta

> [2021-01-27] android-sdk-meta 28.0.2+3 MIGRATED to testing (Debian testing watch)

:tada:

**Comment by rom1v** [comment]
> Well the build-dep android-sdk-meta is buggy so we will almost surely miss this release :/

What's the deadline for the `scrcpy` package? Is it "soft freeze" (feb 12th)? "hard freeze" (march 12th)?

**Pull request closed without merging**
