### PR TITLE
To fix windows build issue and Run adb kill-server when exit.

### PR DESCRIPTION
**Pull request by uhuntu**
```
$ ninja -Cx
ninja: Entering directory `x'
[0/1] Generating scrcpy-server with a custom command
/bin/bash: D:/repos/scrcpy/server/./scripts/build-wrapper.sh: No such file or directory
FAILED: server/scrcpy-server
"bash" "D:/repos/scrcpy/server/./scripts/build-wrapper.sh" "D:/repos/scrcpy/server" "server/scrcpy-server" "debug"
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Comment by uhuntu** [comment]
Also, I realized that when exit the program, the shell will be getting stuck. I used Task Monitor to see the process, there are several adb.exe did not exit correctly.

**Comment by Biswa96** [comment]
I think it is not right thing to kill all adb processes. One adb process can be used for many purposes e.g. debugging, shell etc. Killing that process would also hamper that.

**Comment by npes87184** [comment]
> I think it is not right thing to kill all adb processes. One adb process can be used for many purposes e.g. debugging, shell etc. Killing that process would also hamper that.

I second this.

**Comment by uhuntu** [comment]
The below is the major issue, the system will run below,

```
adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.16 debug 0 8000000 0 -1 false - true true 0 false false -
```

But if you just run ```adb shell``` by ```adb_execute(server->serial, cmd, sizeof(cmd) / sizeof(cmd[0]));```, then the system will never end.

image

```
static process_t
execute_server(struct server *server, const struct server_params *params, bool isIP) {
    char max_size_string[6];
    char bit_rate_string[11];
    sprintf(max_size_string, "%"PRIu16, params->max_size);
    sprintf(bit_rate_string, "%"PRIu32, params->bit_rate);
    char density_string[8+5+1];
    sprintf(density_string,  "density=%"PRIu16, params->density);
    char size_string[5+5+1+5+1];
    snprintf(size_string, sizeof(size_string), "size=%s", params->size ? params->size : "0:0");
    char tablet_string[7+5+1];
    sprintf(tablet_string, "tablet=%s", params->tablet ? "true" : "false");
    char local_port_string[5+5+1];
    sprintf(local_port_string, "port=%u", isIP ? params->local_port : 0);
    char ime_string[7+5+1];
    sprintf(ime_string, "useIME=%s", params->useIME ? "true" : "false");
    char hwolv_string[18+5+1];
    sprintf(hwolv_string, "disableHWOverlays=%s", params->disableHWOverlays ? "true" : "false");

    const char *const cmd[] = {
        "shell",
        "CLASSPATH=/data/local/tmp/" SERVER_FILENAME,
        "app_process",
        "/", // unused
        "com.genymobile.scrcpy.Server",
        max_size_string,
        bit_rate_string,
        server->tunnel_forward ? "true" : "false",
        params->crop ? params->crop : "-",
        "true", // always send frame meta (packet boundaries + timestamp)
        params->control ? "true" : "false",
        density_string,
        size_string,
        tablet_string,
        local_port_string,
        ime_string,
        hwolv_string,
#ifdef WINDOWS_NOCONSOLE
        "fork",
#else
        "forkd",
#endif
    };
    return adb_execute(server->serial, cmd, sizeof(cmd) / sizeof(cmd[0]));
}
```

**Pull request closed without merging**
