### PR TITLE
Add release static builds for Linux (and macOS?)

### PR DESCRIPTION
**Pull request by rom1v**
This is the continuation of my work on #5306.

scrcpy-github-actions

This PR make it possible to build a static release for Linux (x86_64).

For that purpose:
 - `release.mk` is replaced by individual release scripts
 - the dependencies script are made more flexible to select native/cross and static/shared
 - the GitHub Actions script is improved (cf screenshot)
 - a Linux build script is added

Please test the binaries generated by GitHub Actions: https://github.com/Genymobile/scrcpy/pull/5515#issuecomment-2495589621

<details><summary>old</summary>
Here is a Linux binary (x86_64) built by GitHub Actions:

- [`scrcpy-linux-ga.tar.gz`](https://tmp.rom1v.com/scrcpy/5515/1/scrcpy-linux-ga.tar.gz) <sub>`SHA-256: f29f4e915f02c77ab3be4b00aaf218a359248463cc2e423c8ee692621041b62`</sub>
</details>

---

Now, I want to do the same for macOS, but I have no mac. So I started a skeleton (the last commit of this PR), I need your help to complete it and make it work. You can read the commit which adds the static build for Linux as a base.

Thank you!

### CODE REVIEW

**Comment by Genxster1998** [comment]
For macos , macos-latest runner is arch arm64 only.

**Comment by muvaf** [comment]
@rom1v For macOS, I had to fix just small two things but I do see some logs about some missing static libraries https://github.com/Genymobile/scrcpy/pull/5517

**Comment by muvaf** [comment]
@rom1v I can also confirm the build you attached works in Linux amd64:
```
~/Downloads/scrcpy-linux-ga                                                                                                       06:57:27 PM
❯ ./scrcpy_bin
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  localhost:37105                 device  <redacted>
/home/muvaf/Downloads/scrcpy-linux-ga/scrcpy-server: 1 file pushed, 0 skipped. 200.1 MB/s (90228 bytes in 0.000s)
[server] INFO: Device: <redacted> (Android 14)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 560.35.03
INFO: Trilinear filtering enabled
INFO: Texture: 1080x1920
```

**Comment by rom1v** [comment]
@muvaf Thank you!

Can you please test branch `macos_build` (based on your work on #5517)?

**Comment by rom1v** [comment]
@Genxster1998 

> For macos , macos-latest runner is arch arm64 only.

What other runner should we use to build a version for older macos? `macos-14`? They don't provide runners for < 14 apparently: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners

**Comment by muvaf** [comment]
> Could you also please test with ./scrcpy (so that it uses adb and scrcpy-server from the package)?

In Linux amd64, `./scrcpy` works only if I change the last line from `scrcpy "$@"` to `./scrcpy_bin "$@"`.
```
❯ ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_x86_64
./scrcpy-server: 1 file pushed, 0 skipped. 213.4 MB/s (90228 bytes in 0.000s)
[server] INFO: Device: [Google] google sdk_gphone64_x86_64 (Android 15)
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: 
[server] INFO: Retrying with -m2560...
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 560.35.03
INFO: Trilinear filtering enabled
INFO: Texture: 1344x2992
INFO: Texture: 1152x2560
```

**Comment by rom1v** [comment]
> In Linux amd64, ./scrcpy works only if I change the last line from scrcpy "$@" to ./scrcpy_bin "$@".

:facepalm: Thank you, I fixed locally in `app/data/scrcpy_static_wrapper.sh`. :+1:

**Comment by muvaf** [comment]
> Can you please test branch macos_build macos_build.2 (based on your work on https://github.com/Genymobile/scrcpy/pull/5517)?

@rom1v Worked as is!

Similarly, I needed to change the script.
```
> ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_arm64
./scrcpy-server: 1 file pushed, 0 skipped. 236.4 MB/s (71200 bytes in 0.000s)
[server] INFO: Device: [Google] google sdk_gphone64_arm64 (Android 15)
ERROR: Could not get icon path
WARN: Could not load icon
INFO: Renderer: metal
INFO: Texture: 1080x2400
2024-11-23 19:26:07.856 scrcpy_bin[22331:1443939] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-23 19:26:07.856 scrcpy_bin[22331:1443939] +[IMKInputSession subclass]: chose IMKInputSession_Modern
WARN: Killing the server...


> cat scrcpy
#!/bin/bash
cd "$(dirname ${BASH_SOURCE[0]})"
export ADB=./adb
export SCRCPY_SERVER_PATH=./scrcpy-server
export ICON=./icon.png
./scrcpy_bin "$@"
```

**Comment by rom1v** [comment]
For the linux static build, I get this warning:

> WARNING: Static library 'udev' not found for dependency 'libusb-1.0', may not be statically linked

I think this is ok (it just requires udev to be installed at runtime).

**Comment by rom1v** [comment]
> What I'm not sure is that when it says udev not found for dependency libusb-1.0, will it require udev to be present or libusb-1.0

Just `udev`:

```
$ ldd scrcpy_bin 
	linux-vdso.so.1 (0x00007f4b39692000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4b37e7c000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f4b37e37000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b37c41000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b39694000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f4b37c35000)
```

**Comment by muvaf** [comment]
@rom1v This is what I see in macOS with the current `macos_build.2` branch:
```
> otool -L release/work/build-macos/dist/scrcpy_bin
release/work/build-macos/dist/scrcpy_bin:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1351.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 3107.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1226.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
	/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 1000.0.0)
	/System/Library/Frameworks/CoreHaptics.framework/Versions/A/CoreHaptics (compatibility version 1.0.0, current version 1.0.0, weak)
	/System/Library/Frameworks/GameController.framework/Versions/A/GameController (compatibility version 1.0.0, current version 12.1.3, weak)
	/System/Library/Frameworks/ForceFeedback.framework/Versions/A/ForceFeedback (compatibility version 1.0.0, current version 1.0.2)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 170.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 367.4.0, weak)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 61439.41.1)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2575.20.19)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1883.1.10)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 3107.0.0)
```

Given Homebrew reports those as system libraries, I think we're OK, this is probably as static as it gets.

**Comment by muvaf** [comment]
@rom1v 

macOS didn't run at first, asking it to be explicitly allowed in the settings, which I did, then it worked with following logs:
```
 /tmp/scrcpy-macos-test ------------------------------------------------------------------------------------------------------------- 08:34:14 PM
> ls
adb           icon.png      scrcpy        scrcpy-server scrcpy_bin

 /tmp/scrcpy-macos-test --------------------------------------------------------------------------------------------------- KILL  5s  08:34:25 PM
> ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_arm64
./scrcpy-server: 1 file pushed, 0 skipped. 218.7 MB/s (90228 bytes in 0.000s)
[server] INFO: Device: [Google] google sdk_gphone64_arm64 (Android 15)
ERROR: Could not get icon path
WARN: Could not load icon
INFO: Renderer: metal
INFO: Texture: 1080x2400
2024-11-23 20:34:48.398 scrcpy_bin[88997:1891324] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-23 20:34:48.398 scrcpy_bin[88997:1891324] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

**Comment by rom1v** [comment]
> macOS didn't run at first, asking it to be explicitly allowed in the settings

OK, it's probably a security on macOS when running a downloaded binary?

Do you know why these logs:

> 2024-11-23 20:34:48.398 scrcpy_bin[88997:1891324] +[IMKClient subclass]: chose IMKClient_Modern
> 2024-11-23 20:34:48.398 scrcpy_bin[88997:1891324] +[IMKInputSession subclass]: chose IMKInputSession_Modern

?

Do you have them if you build scrcpy yourself (dynamically)?

**Comment by muvaf** [comment]
This is what I see on Linux amd64:
```
/tmp/scrcpy-linux-test                                                                                 08:36:40 PM
❯ ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_x86_64
./scrcpy-server: 1 file pushed, 0 skipped. 225.0 MB/s (90228 bytes in 0.000s)
[server] INFO: Device: [Google] google sdk_gphone64_x86_64 (Android 15)
[server] INFO: Retrying with -m2560...
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: 
libEGL warning: egl: failed to create dri2 screen
[server] WARN: Could not get initial audio timestamp
INFO: Renderer: opengles2
INFO: OpenGL version: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.2
INFO: Trilinear filtering enabled
INFO: Texture: 1344x2992
INFO: Texture: 1152x2560
```

Note that in the first archive you provided in PR description, I was seeing NVIDIA:
```
/tmp/scrcpy-linux-ga                                                                                   08:37:44 PM
❯ ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_x86_64
./scrcpy-server: 1 file pushed, 0 skipped. 104.1 MB/s (90228 bytes in 0.001s)
[server] INFO: Device: [Google] google sdk_gphone64_x86_64 (Android 15)
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: 
[server] INFO: Retrying with -m2560...
[server] WARN: Could not get initial audio timestamp
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 560.35.03
INFO: Trilinear filtering enabled
INFO: Texture: 1344x2992
INFO: Texture: 1152x2560
```


> Do you have them if you build scrcpy yourself (dynamically)?

I haven't built scrcpy myself dynamically

**Comment by rom1v** [comment]
> ERROR: Could not get icon path
> WARN: Could not load icon

Fixed by:

```diff
diff --git app/data/scrcpy_static_wrapper.sh app/data/scrcpy_static_wrapper.sh
index 4dcce9a72..56243471f 100755
--- app/data/scrcpy_static_wrapper.sh
+++ app/data/scrcpy_static_wrapper.sh
@@ -2,5 +2,5 @@
 cd "$(dirname ${BASH_SOURCE[0]})"
 export ADB=./adb
 export SCRCPY_SERVER_PATH=./scrcpy-server
-export ICON=./icon.png
+export SCRCPY_ICON_PATH=./icon.png
 ./scrcpy_bin "$@"
```

**Comment by muvaf** [comment]
@rom1v I'm seeing those log lines even when I use `scrcpy` from `brew install scrcpy`

**Comment by muvaf** [comment]
@rom1v Will you use these scripts only to publish to Github releases or are you planning to use them in Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/scrcpy.rb) as well?

**Comment by rom1v** [comment]
> Note that in the first archive you provided in PR description, I was seeing NVIDIA:

In the initial version, in the build-linux job, I used:

```
          sudo apt install -y meson ninja-build nasm ffmpeg libsdl2-2.0-0 \
             libsdl2-dev libavcodec-dev libavdevice-dev libavformat-dev \
             libavutil-dev libswresample-dev libusb-1.0-0 libusb-1.0-0-dev
```

Now, I use:

```
          sudo apt update
          sudo apt install -y meson ninja-build nasm libudev-dev \
            libasound2-dev libpulse-dev
```

(I added `libasound2-dev` and `libpulse-dev` otherwise I had no sound)

I think I will revert that change, many feature will be missing I guess when building without the SDL and FFmpeg dependencies.

**Comment by rom1v** [comment]
> Will you use these scripts only to publish to Github releases or are you planning to use them in Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/scrcpy.rb) as well?

Only for official releases.

**Comment by muvaf** [comment]
Are you planning on adding linux-arm64 and darwin-amd64 architectures as well potentially via cross-compilation?

**Comment by rom1v** [comment]
> Are you planning on adding linux-arm64 and darwin-amd64 architectures as well potentially via cross-compilation?

It would be great.

However, I won't work on it soon, my goal for now is just to have at least "experimental" static linux and macos releases for "the general use case" before publishing scrcpy 3.0 (with virtual displays and opengl filters).

**Comment by rom1v** [comment]
Here are new binaries, with the known problems fixed:

- [`scrcpy-linux-test.tar.gz`](https://tmp.rom1v.com/scrcpy/5515/3/scrcpy-linux-test.tar.gz) <sub>`SHA-256: a0b60acf0de3b8e8d767b30bc0704dca87ebe62bbeeffc416664a5867484bb8`</sub>
- [`scrcpy-win64-test.zip`](https://tmp.rom1v.com/scrcpy/5515/3/scrcpy-win64-test.zip) <sub>`SHA-256: 0a2baddf716190c23cd39f5c144e2705576a07297e912c922133d24589d2d0b`</sub>
- [`scrcpy-macos-test.tar.gz`](https://tmp.rom1v.com/scrcpy/5515/3/scrcpy-macos-test.tar.gz) <sub>`SHA-256: 2718abe656d28a132c8116130ca776bff7c045d76386b7862aa60230e5885c9`</sub>

Please test :slightly_smiling_face:

**Comment by muvaf** [comment]
macOS arm64:
```
> ./scrcpy
scrcpy 2.7 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  emulator-5554                   device  sdk_gphone64_arm64
./scrcpy-server: 1 file pushed, 0 skipped. 240.2 MB/s (90228 bytes in 0.000s)
[server] INFO: Device: [Google] google sdk_gphone64_arm64 (Android 15)
INFO: Renderer: metal
INFO: Texture: 1080x2400
2024-11-23 21:35:53.362 scrcpy_bin[33048:2055306] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-23 21:35:53.362 scrcpy_bin[33048:2055306] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

**Comment by rom1v** [comment]
To be able to customize variables even with the scrcpy wrapper:

```bash
#!/bin/bash
cd "$(dirname ${BASH_SOURCE[0]})"
export ADB="${ADB:-./adb}"
export SCRCPY_SERVER_PATH="${SCRCPY_SERVER_PATH:-./scrcpy-server}"
export SCRCPY_ICON_PATH="${SCRCPY_ICON_PATH:-./icon.png}"
./scrcpy_bin "$@"
```

```bash
ADB=myadb ./scrcpy
```

@muvaf Could you please confirm that it works fine on macOS. :slightly_smiling_face:

**Comment by Genxster1998** [comment]
@rom1v I have used macos-13 here https://github.com/Genxster1998/scrcpy/commit/db019004aeda96f6083b6c25645f36a760af4de7

**Comment by rom1v** [comment]
@Genxster1998 Could you please re-implement this on top of current `dev` and open a PR, please? (with minimal changes compared to the macos-latest job)

**Comment by muvaf** [comment]
@rom1v FYI, I tested released tarballs in both Linux amd64 and macOS arm64 and they both worked just as expected. Thank you for getting the scripts to the finish line so that we get the static builds so soon!

**Comment by Genxster1998** [comment]
@rom1v I don't have much idea about cross compiling with universal binary as target. It would just need  separate build config for Intel and arm64. And ofcourse renaming release because current macos release in not universal.

**Comment by LeeBinder** [comment]
> @rom1v I have used macos-13 here [Genxster1998@db01900](https://github.com/Genxster1998/scrcpy/commit/db019004aeda96f6083b6c25645f36a760af4de7)

I can confirm your [latest Intel binary from Actions](https://github.com/Genxster1998/scrcpy-old/actions/runs/11261791172#artifacts) build-macos-x86_64-intermediate also running just fine in the latest macOS Monterey 12.7.7

**Comment by Genxster1998** [comment]
@LeeBinder  👍 I am encountering you a lot , in  hacintosh repos , sometime in kernelsu or zygisk stuffs. 🤣

**Comment by LeeBinder** [comment]
..maybe I'm your cyberspace twin brother 🤣 😜

**Comment by Genxster1998** [comment]
@LeeBinder Can you see if https://github.com/Genxster1998/scrcpy/actions/runs/12015099730 works without a local wrapper script , just icon.png and scrcpy-server in same dir and adb installed.

**Comment by LeeBinder** [comment]
YES, you DID it! Executing scrcpy_bin has the desired result, with the icon in the dock - respect!

BTW, in the info for scrcpy_bin it says "requires macOS 13", but it runs fine even in macOS 12 Monterey (maybe even below).

**Comment by rom1v** [comment]
Please test #5644 release builds with `scrcpy --video-codec=av1` (with a phone having an AV1 encoder).

**Pull request merged**
