### PR TITLE
Update README's Brazilian Portuguese translation to 1.17 version

### PR DESCRIPTION
**Pull request by natanjunges**

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

@latreta, as the author of #1313, could you review, please?

**Comment by latreta** [comment]
Might be able to review it later @rom1v

**Review by latreta — APPROVED** [review]
Good to go.

**Comment by rom1v** [comment]
Thank you :+1:

Merged into `master`: af516e33ee2561dfe57b30cfe557bd134a6b50cc

**Pull request closed without merging**
