### PR TITLE
Add a logo to scrcpy, add Windows launcher and custom tile

### PR DESCRIPTION
**Pull request by srevinsaju**
new file:   VisualElements/MediumIconguiscrcpy_Metadata.xml
	new file:   VisualElements/SmallIconguiscrcpy.png
	new file:   VisualElements/SmallIconguiscrcpy_Metadata.xml
	modified: app/src/icon.xpm :: icon
	new file:   icons/android.xpm
	new file:   icons/guiscrcpy_logo.png
	new file:   icons/guiscrcpy_logo.svg 
	new file:   scrcpy.VisualElementsManifest.xml :: Give custom windows tile like PowerPoint tile etc,

Add logo inherited from [guiscrcpy](https://github.com/srevinsaju/guiscrcpy) 
guiscrcpy_logo

In relation for #296 and #295 for Linux, a supposedly alternative for the gparted icon.
Logo under Creative Commons 4.0, own-work,  so easy to distribute.

PS: I am new to Pull Requests and struggled a lot to do this simple stuff ;)

### CODE REVIEW

**Comment by BEEEEEG-YOSHI** [comment]
looks very nice

**Comment by colicrod** [comment]
please,,, those are horrible >_< no offense...

**Comment by rom1v** [comment]
Thank you for your image. But I prefer to keep the current icon, more simple. :wink:

**Comment by jjfurkan** [comment]
Hi I am writing a Linux Guide and I'll publish it when it has enough guide in it. Can I use your icon-work on my site.

**Comment by srevinsaju** [comment]
@jjfurkan if you like it, you may. It is licensed under CC-BY-4.0, so you can use it anywhere you like. 

-----------
[Original picture](https://github.com/srevinsaju/guiscrcpy)

**Comment by thearthurdev** [comment]
@jjfurkan Did you ever finish the guide? I wrote one of my own [here](https://arthur.hashnode.dev/scrcpy-mirror-your-devices-screen-linux-edition-ckd7emcc7002255s127spg8dy) but I would like to see another take on it :D

**Pull request closed without merging**
