### PR TITLE
Add OTG mode (HID only)

### PR DESCRIPTION
**Pull request by rom1v**
Add an option `--otg` to run scrcpy with only physical keyboard (#2632) and mouse (#2916) simulation, without mirroring and without requiring adb (USB debugging), as if the computer keyboard and mouse were plugged directly to the device via an OTG cable.

```bash
scrcpy --otg
# Pass the serial if several USB devices are available
scrcpy --otg -s 0123456789abcdef
```

This opens a window (with just the scrcpy logo, there is no mirroring), which when focused forwards the keyboard and mouse to the device:

otg

The mouse capture works the same way as in "normal" mode (as explained in #2916):
 - when the mouse is "captured", the mouse pointer disappears from the computer and appears on the Android device
 - a click in the window captures the mouse
 - special captures keys, either <kbd>Alt</kbd> or <kbd>Super</kbd>, toggle (disable or enable) the mouse capture (use one of them to give the control of the mouse back to the computer)

Like `--hid-keyboard` and `--hid-mouse`, `--otg` only works if the device is connected by USB, and is currently only supported on Linux.

### CODE REVIEW

**Comment by lucas-bortoli** [comment]
This is awesome! Nice work!

**Comment by BachoSeven** [comment]
@rom1v Would it be possible to also add mirroring to this OTG mode which doesn't require USB debugging? This would be especially useful for broken screens :'D 

thanks in advance

**Comment by rom1v** [comment]
@BachoSeven This is not possible without installing an app on the device and authorizing capture, so that would not work with a broken screen.

**Comment by vielavlrs** [comment]
I tried installing scrcpy v1.22 on Ubuntu 20.04 but the terminal shows my scrcpy is still v1.12? How do I run v1.22 in Ubuntu 20.04?

**Comment by rom1v** [comment]
> I tried installing scrcpy v1.22 on Ubuntu 20.04 but the terminal shows my scrcpy is still v1.12? How do I run v1.22 in Ubuntu 20.04?

Uninstall the one from the distribution (`apt remove scrcpy`), and [follow these steps](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple) to install the latest release.

**Pull request merged**
