### PR TITLE
add dispatch_to_vd option to server

### PR DESCRIPTION
**Pull request by mengyanshou**
Related issue #5137
Fix input event do not work when screen virtual display

### CODE REVIEW

**Comment by mengyanshou** [comment]
As far as I know, the corresponding scrcpy client also needs to add the corresponding parameters.

**Comment by rom1v** [comment]
Please test #5370: does it fixes this problem (without using the `--new-display` feature)?

**Comment by mengyanshou** [comment]
> Please test #5370: does it fixes this problem (without using the `--new-display` feature)?

thanks~see https://github.com/Genymobile/scrcpy/pull/5370#issuecomment-2411152853

**Comment by rom1v** [comment]
Superseded by #5370.

**Pull request closed without merging**
