### PR TITLE
please surpport adb shell input --ext-display  tap x,x   on android 9

### PR DESCRIPTION
**Pull request by gfzhy**
adb shell input --ext-display tap/swipe...   This   commend can sending event to extented display,
so it is very useful  for    scrcpy  --display  2   .
  it also  can solve  the  issue  "Input events are not supported for secondary displays before Android 10".  
Because   "adb shell input --ext-display keyevent <keycode> "  can  send input  to secondary displays  on android 9.

Thank  you  very much.

### CODE REVIEW

**Comment by gfzhy** [comment]
> Thank you very much.

C:\Users\平时>adb shell input
Usage: input [--ext-display] [<source>] <command> [<arg>...]

The sources are:
      dpad
      keyboard
      mouse
      touchpad
      gamepad
      touchnavigation
      joystick
      touchscreen
      stylus
      trackball

The commands and default sources are:
      text <string> (Default: touchscreen)
      keyevent [--longpress] <key code number or name> ... (Default: keyboard)
      tap <x> <y> (Default: touchscreen)
      swipe <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
      draganddrop <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
      press (Default: trackball)
      roll <dx> <dy> (Default: trackball)
      keydown  <keycode> (Default: keyboard)
      keyup  <keycode> (Default: keyboard)
### **_The ext-screen support:
      --ext-display, sending event to extented display_**

**Comment by rom1v** [comment]
Please open an issue instead of a pull request.

> adb shell input --ext-display tap/swipe..

What is this parameter `--ext-display`?

It seems it does not exist in the source code of the `input` command: https://android.googlesource.com/platform/frameworks/base.git/+/master/cmds/input/src/com/android/commands/input/Input.java

**Comment by gfzhy** [comment]
> Please open an issue instead of a pull request.
> 
> > adb shell input --ext-display tap/swipe..
> 
> What is this parameter `--ext-display`?
> 
> It seems it does not exist in the source code of the `input` command: https://android.googlesource.com/platform/frameworks/base.git/+/master/cmds/input/src/com/android/commands/input/Input.java

--ext-display  means  send event to extented display  ,  
when secondary displays started  ,  that  commend  appears.
That  commend  is on  some  phone  that  surpport   displayport

**Comment by gfzhy** [comment]
> Please open an issue instead of a pull request.
> 
> > adb shell input --ext-display tap/swipe..
> 
> What is this parameter `--ext-display`? (oh it's maybe a vendor specific feature, what is the device?)
> 
> It seems it does not exist in the source code of the `input` command: https://android.googlesource.com/platform/frameworks/base.git/+/master/cmds/input/src/com/android/commands/input/Input.java
The device  is  android phone  smartisan  nut  pro3,based on  android 9,
the commend  can control  samrtisan  tnt  mode.

**Pull request closed without merging**
