### PR TITLE
Added scrcpy-server to .gitignore

### PR DESCRIPTION
**Pull request by amirsina-mashayekh**
Added scrcpy-server to .gitignore so that it is ignored by git after running install_release.sh

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

I added a `/` to just ignore the file in the repo root directory, and reworded the commit message: 90ca46ee415514513da9dff8c558d726c8e34318

Please check that everything is ok, then i'll merge.

**Comment by amirsina-mashayekh** [comment]
That's ok. Please merge.

> Thank you 👍
> 
> I added a `/` to just ignore the file in the repo root directory, and reworded the commit message: [90ca46e](https://github.com/Genymobile/scrcpy/commit/90ca46ee415514513da9dff8c558d726c8e34318)
> 
> Please check that everything is ok, then i'll merge.

Looks ok. Please merge. 👍

**Comment by amirsina-mashayekh** [comment]
> Thank you 👍
> 
> I added a `/` to just ignore the file in the repo root directory, and reworded the commit message: [90ca46e](https://github.com/Genymobile/scrcpy/commit/90ca46ee415514513da9dff8c558d726c8e34318)
> 
> Please check that everything is ok, then i'll merge.

That's ok, please merge. 👍

**Comment by rom1v** [comment]
Merged :+1: 90ca46ee415514513da9dff8c558d726c8e34318

**Pull request closed without merging**
