### PR TITLE
Just a couple of new command line options. Borderless and window position.

### PR DESCRIPTION
**Pull request by dedosmedia**
I have made some simple changes (I am not C developer, so I tried to do follow your code... not sure my changes are right)

* Added -B --borderless option.  Make the scrcpy window borderless
* Added -x --pos-x option.  Moves the scrcpy window horizontally
* Added -y --pos-y option.  Moves the scrcpy window vertically

### CODE REVIEW

**Comment by rom1v** [comment]
Oh, sorry, I totally forgot this PR. I will try to review soon.

**Comment by dedosmedia** [comment]
Don't worry. Just some simple commands that I needed for a project, maybe not many people is going to use them.

**Comment by rom1v** [comment]
Out of curiousity, why did you need borderless?

**Comment by dedosmedia** [comment]
I have a Windows PhotoBooth app using a C920 webcam.  I am trying to replace the webcam stream with the Android screen.  So, I am placing the scrcpy window (TOPMOST) above my photobooth window (which is running fullscreen, behind scrcpy) to display the Android screen as if it were a webcam (I am developing an AR app using AR Core). 
I use borderless/position to place the scrcpy window exactly where I need.  
Without borderless, it looks ugly, it's evident I have one app placed over another one because of the border/controls, etc.
With borderless scrcpy window looks integrated into my APP's GUI.  No one notices there are two apps running at the same time.

I was trying to create a virtual webcam from the scrcpy window, so I could just choose the virtual webcam into my app, but I was not able to do it, so this is the workaround I found. Not the right one, but at least works for me.

BTW, thanks so much for such a useful tool. 
I would be happy to donate some money but I think you are not receiving donations as this is something genymobile paid.  Anyway, thanks so much! Great effort, great tool and wonderful developer..

**Comment by rom1v** [comment]
> With borderless scrcpy window looks integrated into my APP's GUI. No one notices there are two apps running at the same time.

:smile: great trick :+1: Thanks for the details.

> I would be happy to donate some money but I think you are not receiving donations

Indeed, I do not use any system to receive donations. Maybe some day…

> as this is something genymobile paid.

I was employee at Genymobile when I initially developed it (until v1.0~v1.1), so yes, I was paid for developing it. Since then, it's on my free time :wink:

Thank you for your message.

**Comment by rom1v** [comment]
Hi,

Sorry for the delay.

I rebased your commit on `dev`.
I split it into two commits (one for window position, one for borderless).
I renamed `--pos-x` and `--pos-y` to `--window-x` and `--window-y` (and disabled the "short argument" versions, I want to keep letters free for main options :wink:).
For completeness, I also implemented `--window-width` and `--window-height`.

Here is the resulting branch: [`window-params`](https://github.com/Genymobile/scrcpy/commits/window-params).

Please review your modified commits, I'll merge them into `dev` next week.

**Comment by rom1v** [comment]
Merged into `dev`.

**Comment by Bubbleioa** [comment]
Thanks a lot, I need borderless window too. Because my phone srceen is a Rounded Rectangle

**Pull request closed without merging**
