### PR TITLE
Remove unnecessary escape characters in manpage

### PR DESCRIPTION
**Pull request by yangfl**

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

Your commit e-mail is currently `yangfl@users.noreply.github.com` (like other commits of yours in this repo). Could I change it to a real e-mail?

**Comment by yangfl** [comment]
OK, it's up to you.

**Comment by rom1v** [comment]
OK, which e-mail should I use? `mmyangfl` at gmail?

**Review by Relluem94 — APPROVED** [review]

**Comment by rom1v** [comment]
Merged: 1863ca7ad1b87f9b32aa1c5aa9554741f5845fba

**Pull request closed without merging**
