### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by rootkea**

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

1st commit: :heavy_check_mark: 
 - I added the same change in the implementation file
 - I reworded the commit message for the git 50-72 rule

2nd commit: :heavy_check_mark: 

3rd commit: :x:
 - the `SC_VECTOR` is internal to the implementation, and does not need to be exposed
 - there is already `sc_usb_devices_destroy_all()` which works on any array of `sc_usb_device` (including "vectors")

Branch [pr4371](https://github.com/Genymobile/scrcpy/commits/pr4371).

**Comment by rom1v** [comment]
Merged into `dev`.

**Comment by rootkea** [comment]
Hey @rom1v since we haven't tagged the repo with the "hacktoberfest" label, could you please tag this PR with "hacktoberfest-accepted" label? Thanks!

**Comment by rom1v** [comment]
Scrcpy does not participate in hacktoberfest.

In their [maintainer](https://hacktoberfest.com/participation/#maintainers) page, they say:

> Be ready to review pull/merge requests, accepting those that are valid by merging them, **leaving an overall approving review**, or by adding the “hacktoberfest-accepted” label.

I definitely "left an overall approving review" (since the commits have been merged), it should be sufficient. Let me know if it isn't in the end.

**Pull request closed without merging**
