### PR TITLE
Add --tcpip option to automate TCP/IP (wireless) connections

### PR DESCRIPTION
**Pull request by rom1v**
Add an option to configure the TCP/IP connection automatically. There are two variants.

If the device (accessible at 192.168.1.1 in this example) already listens on a port (typically 5555) for incoming adb connections, then run:

```bash
scrcpy --tcpip=192.168.1.1       # default port is 5555
scrcpy --tcpip=192.168.1.1:5555
```

If the device TCP/IP mode is disabled (or if you don't know the IP address), connect the device over USB, then run:

```bash
scrcpy --tcpip    # without arguments
```

It will automatically find the device IP address (by parsing `adb shell ip route`), enable TCP/IP mode, then connects to the device before starting.

---

Here are binaries so that you can test easily. Please replace these files in your v1.20 release:

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2827/4/scrcpy.exe) _sha256:c3d96408d81d4c3f17259a8d99bd2e343f6c9758dc85e6317b114f6cdc95fd00_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2827/4/scrcpy-server) _sha256:e08e9aa4796c213bf601f6323b5e9f4fce250b1f3b1d46441289824cb4af294a_

<details><summary>old binaries v3</summary>

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2827/3/scrcpy.exe) _sha256:67068f06190a5454ca245290022da84549a8d23c5c90926ddf2a558a20e2d0f8_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2827/3/scrcpy-server) _sha256:e08e9aa4796c213bf601f6323b5e9f4fce250b1f3b1d46441289824cb4af294a_

</details>

<details><summary>old binaries v2</summary>

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2827/2/scrcpy.exe) _sha256:1931c1637fb35c453d35b416cc0bcbefcf25806f79d52eb3cec3d5fc78a26a05_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2827/2/scrcpy-server) _sha256:e08e9aa4796c213bf601f6323b5e9f4fce250b1f3b1d46441289824cb4af294a_

</details>

<details><summary>old binaries v1</summary>

 - [`scrcpy.exe`](https://tmp.rom1v.com/scrcpy/2827/1/scrcpy.exe) _sha256:e77f3140f90353ad5b724576df9f1223717c24927ea4255714c122d5a956451a_
 - [`scrcpy-server`](https://tmp.rom1v.com/scrcpy/2827/1/scrcpy-server) _sha256:e08e9aa4796c213bf601f6323b5e9f4fce250b1f3b1d46441289824cb4af294a_

</details>

Please test and report any issue you might encounter. This is also built from the current `dev` branch (so with code which will be in the next release), where I did a lot of refactors recently, so please report any regression. That would help a lot :wink: 

Thank you for your feedback.

### CODE REVIEW

**Comment by Helaer** [comment]
> 

@rom1v  I have a Huawei mobile phone and a Xiaomi mobile phone, I did a test separately, scrcpy --tcpip=192.168.1.1 # default port is 5555
scrcpy --tcpip=192.168.1.1:5555 These two options are no problem,You can directly connect to the device IP address and start the screen projection window. The scrcpy --tcpip # without arguments option is only valid on my Huawei phone, and on Xiaomi phones Unable to automatically connect to IP.

**Comment by Helaer** [comment]
> shell ip route

Huawei mobile phone obtains IP log:
D:\scrcpy-win64-v1.20>adb -s 66J5T19614020092 shell ip route
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.6

Xiaomi mobile phone obtains IP log:
D:\scrcpy-win64-v1.20>adb -s e2b16c shell ip route
10.90.227.156/30 dev rmnet_data4 proto kernel scope link src 10.90.XXX.XXX
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.7

Both mobile phones are connected to the Wi-Fi network at the same time. The difference is that the phone card is not inserted in the Huawei mobile phone, and the phone card is inserted in the Xiaomi mobile phone. I think you should start with the analysis of keywords in dev wlan0 proto kernel scope link src.

**Comment by rom1v** [comment]
OK, thank you for your test.

For now, it always get the ip from the first line of `adb shell ip route`. I will change to consider the first line where the 3rd column starts with `wlan`.

**Comment by rom1v** [comment]
I pushed a new version, please re-test :wink:

**Comment by Helaer** [comment]
@rom1v I tested it on Xiaomi and Huawei devices respectively, and --tcpip and --raw-key-events both work well.

**Comment by sbfkcel** [comment]
@rom1v Can you increase support for websocket

**Pull request merged**
