### PR TITLE
add --window-title options with %M and %S variable replacement

### PR DESCRIPTION
**Pull request by beango1**
solves issue #120 
continuation of #573

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you for your PR. It works :+1:

However, I'm wondering if we shouldn't replace the variables on the server side instead:
 - their value are device-specific values, known by the device;
 - all variables are not always used (typically, they are not), so it's useless to transmit them all (more will be available in the future, see #601) just to ignore them on the client side;
 - implementing a new variable would not require to modify the protocol between the server and the client;
 - Java is much safer for string manipulation.

What do you think?

**Comment by beango1** [comment]
Fair points.  Perhaps for next iterations.

After doing all of the changes, I think it would have been cleaner just to
set the window title the vanilla way.  Let the user set the it the way they
like ;)

**Comment by rom1v** [comment]
> After doing all of the changes, I think it would have been cleaner just to set the window title the vanilla way.

A first separate commit doing just that would still be great :wink:

**Comment by beango1** [comment]
#616

**Pull request closed without merging**
