### PR TITLE
Add macOS intel64 build-action

### PR DESCRIPTION
**Pull request by Genxster1998**
I just changed runner machine to macos-13.You can check artifacts here.https://github.com/Genxster1998/scrcpy-old/actions/runs/12000259857
For intel machine it is working.
2024-11-25 04 39 45 github com ec1e0c3d3bbd
~~PS: Forgot to reflect changes in  generate-checksums.sh.~~

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

I added preliminary commits, in particular to add the architecture on Linux and macOS.

I renamed intel to x86_64. (Is it ok for you?)

Please review/test [`linux_macos_arch`](https://github.com/Genymobile/scrcpy/commits/linux_macos_arch/).

**Comment by Genxster1998** [comment]
> Thank you 👍

👍 

> I added preliminary commits, in particular to add the architecture on Linux and macOS. I reused the same `build_macos.sh` script to avoid duplication.

👍 

> I renamed intel to x86_64. (Is it ok for you?)

I can't agree more but they do use intel suffix sometimes, you know Apple.

> Please review/test [`linux_macos_arch`](https://github.com/Genymobile/scrcpy/commits/linux_macos_arch/).

i just ran the app from linux_macos_arch branch , it works correctly.

**Comment by rom1v** [comment]
Merged into `dev` :rocket:

**Comment by rom1v** [comment]
FYI

> The macOS 13 hosted runner image is closing down, following our [N-1 OS support policy](https://github.com/actions/runner-images?tab=readme-ov-file#software-and-image-support). This process will begin **October 1, 2025**, and the image will be fully retired on **December 4, 2025**. We recommend updating workflows to use `macos-14` or `macos-15`.

https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down

**Comment by Genxster1998** [comment]
Dang ! 😫
They don't support x86-64. Intel is retired by many mainstream projects like Rust official builds on OSX platform from tier-1.

**Pull request closed without merging**
