### PR TITLE
Use Cmd instead of Ctrl on macOS

### LINKED ISSUE #642: Use Cmd+c/Cmd+c on Mac OS?
On Mac OS, should we use Cmd instead of Ctrl to copy-paste?

If yes, we should ifdef the same way we do for the volume:
https://github.com/Genymobile/scrcpy/blob/49612561233b3cde41339ee08c71892e42649706/app/src/input_manager.c#L293-L297

here:
https://github.com/Genymobile/scrcpy/blob/49612561233b3cde41339ee08c71892e42649706/app/src/input_manager.c#L312-L327

### PR DESCRIPTION
**Pull request by rom1v**
Use `Cmd` instead of `Ctrl` for all shortcuts on macOS.

Fixes #642

---

Mac users, please confirm that it works as expected :wink:

cc @npes87184 @carstenhag @zhuxianfeng13 @AoDevBlue @numbermaniac

### CODE REVIEW

**Comment by carstenhag** [comment]
Hey, I've compiled and tried it out just now.

Cmd+M does not work as excepted, because Cmd+M is a mac (global?) shortcut to minimize the window.

The other shortcuts work fine. One thing though, which I guess is unrelated: I have no way to middle-click on a Magic Mouse. On the Macbook touchpad it's *possible* but really difficult depending on the touchpad settings. It would be good to provide an alternative shortcut for that.

**Comment by rom1v** [comment]
@carstenhag Thank you very much for your tests and feedback.

So I updated this PR to keep `Ctrl` for `Ctrl`+`h` and `Ctrl`+`m`.

> I have no way to middle-click on a Magic Mouse. On the Macbook touchpad it's possible but really difficult depending on the touchpad settings. It would be good to provide an alternative shortcut for that.

What would you suggest? I will probably use `Ctrl`+click or `Shift`+click for "pinch to zoom". Maybe `Ctrl`+Right-click or something like that?

**Comment by carstenhag** [comment]
Yeah, Cmd+Click seems good to me.

**Comment by rom1v** [comment]
Cmd+click for HOME or pinch-to-zoom (not implemented yet)?

**Comment by carstenhag** [comment]
Not really sure what you mean by pinch-to-zoom :) 

Cmd for Home, Shift for that, seems good to me. We can still test it later.

**Comment by rom1v** [comment]
> Not really sure what you mean by pinch-to-zoom :)

https://github.com/Genymobile/scrcpy/issues/24

**Pull request merged**
