### PR TITLE
fix freeze and thaw rotation for Android 15 preview

### PR DESCRIPTION
**Pull request by ssalenik**
On a device with Android 15 developer preview (and I think this also impacts the 14 QPR3 Beta) we get an error when trying to rotate the device:
```
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     --> (tcpip)  26101FDF6003UC           device  Pixel_6
x/server/scrcpy-server: 1 file pushed, 0 skipped. 3.1 MB/s (66691 bytes in 0.020s)
[server] INFO: Device: [Google] google Pixel 6 (Android 14)
INFO: Renderer: metal
INFO: Texture: 360x800
[server] INFO: Device rotation requested: landscape
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.IWindowManager$Stub$Proxy.freezeRotation [int]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.WindowManager.getFreezeRotationMethod(WindowManager.java:48)
        at com.genymobile.scrcpy.wrappers.WindowManager.freezeRotation(WindowManager.java:111)
        at com.genymobile.scrcpy.Device.rotateDevice(Device.java:372)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:183)
        at com.genymobile.scrcpy.Controller.control(Controller.java:85)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:93)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:1012)
```

The source code is not out yet, but using reflection we can see that the freeze and thaw rotation methods all have a new signature with a `String` parameter added:

```
public void android.view.IWindowManager$Stub$Proxy.thawRotation(java.lang.String) throws android.os.RemoteException
public void android.view.IWindowManager$Stub$Proxy.thawDisplayRotation(int,java.lang.String) throws android.os.RemoteException
public void android.view.IWindowManager$Stub$Proxy.freezeRotation(int,java.lang.String) throws android.os.RemoteException
public void android.view.IWindowManager$Stub$Proxy.freezeDisplayRotation(int,int,java.lang.String) throws android.os.RemoteException
```

I tried passing an empty String and it works.

This PR adds these new method signatures to try first.

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you.

Could you please post your framework.jar please?

```
adb pull /system/framework/framework.jar
```

**Comment by ssalenik** [comment]
[framework.jar.tar.gz](https://github.com/Genymobile/scrcpy/files/14530375/framework.jar.tar.gz)

**Comment by rom1v** [comment]
> jadx.plugins.input.dex.DexException: Bad checksum: 0x6dca9986, expected: 0x962f5582

:thinking:

**Comment by ssalenik** [comment]
I got the same thing. You can ignore the checksum with `jadx -Pdex-input.verify-checksum=no` but I didn't find these methods nor the `WindowManager` class in the decompiled code after, though it had a few errors in decompilation.

**Comment by ssalenik** [comment]
Looks like they published the source for this change in master now:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/IWindowManager.aidl#345
The parameter is `String caller`, though they don't describe the parameter:
```
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/IWindowManager.aidl#345
```

**Comment by ssalenik** [comment]
Ah, thanks. Makes sense. I guess we can add "scrcpy" or "scrcpy#setRotation" and "scrcpy#restoreRotationStateLocked" to  follow their lead.

**Comment by rom1v** [comment]
Thank you :+1:

I added a preliminary commit to refactor the current codebase: 4623927d300e9a6edcb9074abc9e144d4c2e3286.
Then I rebased your PR on this commit (using the new version field): 803a7e0d866e5a9605008cb1540ebc168d6c2aa2

I pushed to branch `pr4740`. Please review and test :wink:

**Comment by ssalenik** [comment]
@rom1v tested `pr4740` and works on Android 15 preview

**Comment by rom1v** [comment]
Btw, it seems the change has landed in Android 14 (stable, not preview), on a Pixel 8 without this PR I get the error on rotation with MOD+r.

```
$ git tag --contains 670fb7f5c0d23cf51ead25538bcb017e03ed73ac
android-14.0.0_r29
android-14.0.0_r30
android-14.0.0_r31
```

**Comment by rom1v** [comment]
Merged into `dev`: 7011dd1ef0fe0f745387251c0a97bac338ce767d

**Comment by eiyooooo** [comment]
https://github.com/Genymobile/scrcpy/blob/7011dd1ef0fe0f745387251c0a97bac338ce767d/server/src/main/java/com/genymobile/scrcpy/wrappers/WindowManager.java#L49-L106

Should try the newest method first, then old method.

Because the old method still exists while the new method is introduced.

**Comment by rom1v** [comment]
> Because the old method still exists while the new method is introduced.

Nope, it was replaced: https://android.googlesource.com/platform/frameworks/base/+/670fb7f5c0d23cf51ead25538bcb017e03ed73ac%5E%21/

**Comment by eiyooooo** [comment]
> Nope, it was replaced: https://android.googlesource.com/platform/frameworks/base/+/670fb7f5c0d23cf51ead25538bcb017e03ed73ac%5E%21/

While `freezeDisplayRotation` is introduced, `freezeRotation` still exists.

If try `freezeRotation` first, then could not rotate secondary display.

```
C:\q\software\scrcpy-win64-v2.4>scrcpy.exe --display-id 67
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R5CN2100000                     device  SM_G986U1
C:\q\software\scrcpy-win64-v2.4\scrcpy-server: 1 file pushed, 0 skipped. 29.5 MB/s (69259 bytes in 0.002s)
[server] INFO: Device: [samsung] samsung SM-G986U1 (Android 13)
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: Renderer: direct3d
INFO: Texture: 1080x1920
[server] ERROR: Secondary display rotation not supported on this device
[server] INFO: Device rotation requested: landscape
[server] ERROR: Secondary display rotation not supported on this device
[server] ERROR: Secondary display rotation not supported on this device
```

So try `freezeDisplayRotation` first, if `freezeDisplayRotation` not exists then `freezeRotation`.

```
C:\q\software\scrcpy-win64-v2.4>scrcpy.exe --display-id 67
scrcpy 2.4 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)  R5CN2100000                     device  SM_G986U1
C:\q\software\scrcpy-win64-v2.4\scrcpy-server: 1 file pushed, 0 skipped. 84.4 MB/s (69223 bytes in 0.001s)
[server] INFO: Device: [samsung] samsung SM-G986U1 (Android 13)
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: Renderer: direct3d
INFO: Texture: 1080x1920
[server] INFO: Device rotation requested: landscape
INFO: Texture: 1920x1080
[server] INFO: Device rotation requested: portrait
INFO: Texture: 1080x1920
WARN: Killing the server...
```

**Comment by rom1v** [comment]
Oh ok, sorry, I read the whole thing from my phone, I will check later from my computer.

**Comment by ssalenik** [comment]
Oh, oups. I didn't notice that your refactor @rom1v changed this. Before we were trying the methods which allow to specify the `display` first and then falling back to the old one in the case that `display == 0`.

**Comment by rom1v** [comment]
LGTM, see #4841.

**Pull request closed without merging**
