### PR TITLE
Update bug_report.md

### PR DESCRIPTION
**Pull request by Fr-Dae**
visual update:
- with the addition of forgettable capital letters 
- and bold tags to make it easier to read 

(yes, we're thinking of you, nice dev).

### CODE REVIEW

**Comment by Fr-Dae** [comment]
@Genymobile

**Comment by Fr-Dae** [comment]
@rom1v

**Comment by rom1v** [comment]
Merged: 585cff769365f9b8c58af43f0d7adc4c7b899c4f

I also added 126da0cb18576cc40b9506c676af3a2d569c760c and cc8e6133b0c9975ef2ed16086960e822ab750404.

**Comment by Fr-Dae** [comment]
why "closed" and not just validate the PR ?

**Comment by rom1v** [comment]
Because I rebased:
 - on top of current `dev` (I merged other commits beforehand)
 - I edited commit message (I always do, at least to reference the PR)

GitHub does not provide anything to mark a PR as "merged" if you just edit commits manually.

Also read this post from the author of curl: https://daniel.haxx.se/blog/2024/06/11/why-curl-closes-prs-on-github/

Basically, it's always the cases for PR merged in scrcpy (except my owns, because I can push force just before merging).

**Pull request closed without merging**
