### PR TITLE
Flac audio codec

### PR DESCRIPTION
**Pull request by megapro17**
I didn't tested it, compiling is complicated
It would also be nice to have an 8 compression ratio

### CODE REVIEW

**Comment by rom1v** [comment]
Refs https://github.com/Genymobile/scrcpy/pull/3757#issuecomment-1798233408

Small fix to compile:

```diff
diff --git a/app/src/demuxer.c b/app/src/demuxer.c
index ca27c0bc1..69d0c42b7 100644
--- a/app/src/demuxer.c
+++ b/app/src/demuxer.c
@@ -26,7 +26,7 @@ sc_demuxer_to_avcodec_id(uint32_t codec_id) {
 #define SC_CODEC_ID_AV1 UINT32_C(0x00617631) // "av1" in ASCII
 #define SC_CODEC_ID_OPUS UINT32_C(0x6f707573) // "opus" in ASCII
 #define SC_CODEC_ID_AAC UINT32_C(0x00616163) // "aac in ASCII"
-#define SC_CODEC_ID_AAC UINT32_C(0x664c6143) // "fLaC in ASCII"
+#define SC_CODEC_ID_FLAC UINT32_C(0x664c6143) // "fLaC in ASCII"
 #define SC_CODEC_ID_RAW UINT32_C(0x00726177) // "raw" in ASCII
     switch (codec_id) {
         case SC_CODEC_ID_H264:
diff --git a/app/src/options.h b/app/src/options.h
index 5a37b1311..914338946 100644
--- a/app/src/options.h
+++ b/app/src/options.h
@@ -33,7 +33,7 @@ sc_record_format_is_audio_only(enum sc_record_format fmt) {
     return fmt == SC_RECORD_FORMAT_M4A
         || fmt == SC_RECORD_FORMAT_MKA
         || fmt == SC_RECORD_FORMAT_OPUS
-        || fmt == SC_RECORD_FORMAT_AAC;
+        || fmt == SC_RECORD_FORMAT_AAC
         || fmt == SC_RECORD_FORMAT_FLAC;
 }
 
```

But at runtime, I get:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==190749==ERROR: AddressSanitizer: FPE on unknown address 0x7fe68841b808 (pc 0x7fe68841b808 bp 0x000000001000 sp 0x7fe619ea9520 T25)
    #0 0x7fe68841b808  (/lib/x86_64-linux-gnu/libswresample.so.4+0x10808) (BuildId: ddc2f6bd89b08150e9399afd21a7bd46803246da)
    #1 0x7fe68841c4a5  (/lib/x86_64-linux-gnu/libswresample.so.4+0x114a5) (BuildId: ddc2f6bd89b08150e9399afd21a7bd46803246da)
    #2 0x7fe68841d519 in swr_convert (/lib/x86_64-linux-gnu/libswresample.so.4+0x12519) (BuildId: ddc2f6bd89b08150e9399afd21a7bd46803246da)
    #3 0x563d190dee3c in sc_audio_player_frame_sink_push ../app/src/audio_player.c:156
    #4 0x563d1911817c in sc_frame_source_sinks_push ../app/src/trait/frame_source.c:53
    #5 0x563d190ec708 in sc_decoder_push ../app/src/decoder.c:66
    #6 0x563d190ec7d8 in sc_decoder_packet_sink_push ../app/src/decoder.c:94
    #7 0x563d1911881b in sc_packet_source_sinks_push ../app/src/trait/packet_source.c:53
    #8 0x563d190ef615 in run_demuxer ../app/src/demuxer.c:257
    #9 0x7fe6860c3408  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xa4408) (BuildId: 212fce418ad3777e67ef93d7a228ba10d4e8fb51)
    #10 0x7fe686168fec  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x149fec) (BuildId: 212fce418ad3777e67ef93d7a228ba10d4e8fb51)
    #11 0x7fe685ca63eb in start_thread nptl/pthread_create.c:444
    #12 0x7fe685d26a4b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE (/lib/x86_64-linux-gnu/libswresample.so.4+0x10808) (BuildId: ddc2f6bd89b08150e9399afd21a7bd46803246da) 
Thread T25 created by T0 here:
    #0 0x7fe687c47c26 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:208
    #1 0x7fe68616905e  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x14a05e) (BuildId: 212fce418ad3777e67ef93d7a228ba10d4e8fb51)

==190749==ABORTING
```

To be investigated.

(Also, an argument to set the compression compression should maybe be added?)

**Comment by megapro17** [comment]
maybe this?
```diff
@@ -25,7 +25,7 @@ enum sc_record_format {
     SC_RECORD_FORMAT_MKA,
     SC_RECORD_FORMAT_OPUS,
     SC_RECORD_FORMAT_AAC,
-    SC_RECORD_FORMAT_FLAC,
+    SC_RECORD_FORMAT_FLAC;
 };
```

**Comment by megapro17** [comment]
> (Also, an argument to set the compression compression should maybe be added?)

would `--audio-codec-options=KEY_FLAC_COMPRESSION_LEVEL=8` work?

**Comment by rom1v** [comment]
> ==190749==ERROR: AddressSanitizer: FPE on unknown address 0x7fe68841b808 (pc 0x7fe68841b808 bp 0x000000001000 sp 0x7fe619ea9520 T25)

If I hardcode this value, it "works":

```diff
diff --git a/app/src/demuxer.c b/app/src/demuxer.c
index 69d0c42b7..520ac609e 100644
--- a/app/src/demuxer.c
+++ b/app/src/demuxer.c
@@ -210,6 +210,7 @@ run_demuxer(void *data) {
         codec_ctx->channels = 2;
 #endif
         codec_ctx->sample_rate = 48000;
+        codec_ctx->sample_fmt = AV_SAMPLE_FMT_S16;
     }
 
     if (avcodec_open2(codec_ctx, codec, NULL) < 0) {
```

But another problem is that the flac encoder is not low latency at all: it produces blocks of 4096 samples, which represent ~85.333ms.

So to make it work, the audio latency must be increased:

```
scrcpy --audio-codec=flac --audio-buffer=200
```

😕

**Comment by megapro17** [comment]
can you share binary for windows? even without ffmpeg dlls 

> mp4 does not support flac

it does, opus too. by the official mpeg specification. most players can play these files fine. ffmpeg can create it without problems

> flac encoder is not low latency at all

seems like there's no any other lossless audio encoder built in android... i guess you don't need low latency when recording to a file

**Comment by rom1v** [comment]
> can you share binary for windows? even without ffmpeg dlls

- [`scrcpy-flac.zip`](https://tmp.rom1v.com/scrcpy/4410/1/scrcpy-flac.zip) <sub>`SHA-256: d740ce526d2ed66939d531a2447306e67a25e6a3f231ff0a0651b820298e1e43`</sub>

(only the .exe and the server, not tested)


> > mp4 does not support flac
>
> it does, opus too. by the official mpeg specification. most players can play these files fine. ffmpeg can create it without problems

For some reason, the call to `av_write_trailer()` returns `AVERROR_INVALIDDATA`:

https://github.com/Genymobile/scrcpy/blob/446ea818a44eb75f03f21d08d307801b20ca2871/app/src/recorder.c#L428

**Comment by megapro17** [comment]
It does play audio, but it doesn't record it. After recording, file is broken. It seems like it has two fLaC signatures. If i remove the first one, it doesn't show errors, but still can't play, because length is 0 seconds 
image

```
[flac @ 0000023fcb0b1980] extradata too small.
[matroska,webm @ 0000023fcb0ae780] Failed to open codec in avformat_find_stream_info
[flac @ 0000023fcb0b1980] extradata too small.
[matroska,webm @ 0000023fcb0ae780] Could not find codec parameters for stream 1 (Audio: flac, 48000 Hz, 0 channels): unspecified number of channels
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[aist#0:1/flac @ 0000023fcb0fcb00] Guessed Channel Layout: stereo
Input #0, matroska,webm, from '1.mkv':
  Metadata:
    COMMENT         : Recorded by scrcpy v2.2
    ENCODER         : Lavf60.17.100
  Duration: 00:00:07.84, start: 0.000000, bitrate: 3906 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 1440x3088, 1k tbr, 1k tbn
    Metadata:
      DURATION        : 00:00:07.836000000
  Stream #0:1: Audio: flac, 48000 Hz, 2 channels
    Metadata:
      DURATION        : 00:00:07.686000000
At least one output file must be specified
```
i removed first fLaC from mkv and this file can be converted to wav...

**Comment by rom1v** [comment]
OK, so I guess the extradata produced by `MediaCodec` does not have the format expected by FFmpeg, so it has to be transformed, like we do for opus (but it looks like it's yet another format):

https://github.com/Genymobile/scrcpy/blob/446ea818a44eb75f03f21d08d307801b20ca2871/server/src/main/java/com/genymobile/scrcpy/Streamer.java#L103-L117

**Comment by rom1v** [comment]
I made the following changes:
 - rebased on `dev`
 - generated FFmpeg build with FLAC support for Windows (and upgraded to FFmpeg 6.1 released yesterday)
 - fixed flac config packet for ffmpeg
 - automatically increased the default audio buffer when flac is used
 - updated documentation

Branch: [`flac.3`](https://github.com/Genymobile/scrcpy/commits/flac.3)

Here is a full release of that branch:

- [`scrcpy-flac.zip`](https://tmp.rom1v.com/scrcpy/4410/2/scrcpy-flac.zip) <sub>`SHA-256: 0305560795e4d4ebf465d3d8b8a5a0ad3c112ba9131736a723bc7fee91aeae25`</sub>

Please review and test.

**Comment by megapro17** [comment]
Wow, nice work! Everything works now, audio is recorded and played without any problems. But the file has no duration, to fix it I have to convert the file. But isn't that fixConfigPacket for each codec is looks weird? Maybe there is a more elegant solution.....

**Comment by rom1v** [comment]
> But the file has no duration, to fix it I have to convert the file.

Indeed, when a FLAC audio stream is muxed to flac (`.flac` file), there is no global duration.

However, for an OPUS audio stream muxed to opus (`.opus` file), or an AAC audio stream muxed to mp4 (`.aac`), it works correctly, the global duration is correctly written.

Similarly, when a FLAC audio stream is muxed to MP4 (`.mp4`) or Matroska (`.mkv`), it also works.

So I guess this is related to the flac muxer, it does not write the duration when writing the trailer. I don't know if we can pass some more configuration so that it correctly writes the duration.

Related code: https://github.com/FFmpeg/FFmpeg/blob/6d60cc7baf662b64e3c50f95826dead58cf8e839/libavformat/flacenc.c#L320-L346

> But isn't that fixConfigPacket for each codec is looks weird?

It's just that MediaCodec wraps the extradata into its own structure (different per codec), so we have to extract the relevant extradata to pass to FFmpeg.

**Comment by rom1v** [comment]
Above these changes, I added support for recording raw audio to `.wav` or `.mkv`/`.mka`.

Branch: [`wav.6`](https://github.com/Genymobile/scrcpy/commits/wav.6)

- [`scrcpy-wav.6.zip`](https://tmp.rom1v.com/scrcpy/4410/3/scrcpy-wav.6.zip) <sub>`SHA-256: fbaf241c10a2d640c4100c39bff46cce4ebdc2e70d44e81adbfd119437f8a958`</sub>

```
scrcpy --audio-codec=raw --record=file.mkv
scrcpy --audio-codec=raw --no-video --record=file.wav
```

Please review and test :wink:

**Comment by rom1v** [comment]
I merged flac and wav support into `dev`.

If we find a way to fix the missing flac duration, that would be great, but this can still be merged as is.

**Pull request closed without merging**
