### PR TITLE
Restart capture when screen resolution changes

### LINKED ISSUE #161: Screen problems after adjusting the resolution.
After decrease the resolution and resize window, the window will still leave a black space on the right and bottom. And show background screen beyond set screen size on home screen.

### LINKED ISSUE #1918: Doesn't sync correctly after use adb shell wm size.
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Ubuntu 18.04
 - scrcpy version: 1.14
 - installation method: apt
 - device model: Redmi note 8 pro (begonia) <- 1080x2336 default.
 - Android version: 10

**Describe the bug**
1. start scrcpy
2. run `adb shell wm size 1080x2336` or  `adb shell wm size 1080x1920`
3. scrcpy stdout nothing and the copied screen was not fully displayed.

terminal 1(scrcpy):
```
sodiumaluminate@AlsPad:~$ scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server:...shed. 5.7 MB/s (33142 bytes in 0.006s)
[server] INFO: Device: Xiaomi Redmi Note 8 Pro (Android 10)
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 450.80.02
INFO: Trilinear filtering enabled
INFO: Initial texture: 1080x2336
^CWARN: Device disconnected
sodiumaluminate@AlsPad:~$ 
```

terminal 2(adb wm):
```
sodiumaluminate@AlsPad:~$ adb shell 
begonia:/ $ wm 
Window manager (window) commands:
  help
      Print this help text.
  size [reset|WxH|WdpxHdp] [-d DISPLAY_ID]
    Return or override display size.
    width and height in pixels unless suffixed with 'dp'.
  density [reset|DENSITY] [-d DISPLAY_ID]
    Return or override display density.
  folded-area [reset|LEFT,TOP,RIGHT,BOTTOM]
    Return or override folded area.
  overscan [reset|LEFT,TOP,RIGHT,BOTTOM] [-d DISPLAY ID]
    Set overscan area for display.
  scaling [off|auto] [-d DISPLAY_ID]
    Set display scaling mode.
  dismiss-keyguard
    Dismiss the keyguard, prompting user for auth if necessary.
  set-user-rotation [free|lock] [-d DISPLAY_ID] [rotation]
    Set user rotation mode and user rotation.
  set-fix-to-user-rotation [-d DISPLAY_ID] [enabled|disabled]
    Enable or disable rotating display for app requested orientation.
255|begonia:/ $ wm size 1080x1920                                                                                                                    
begonia:/ $ wm size reset                                                                                                                            
begonia:/ $ wm size 1080x1920                                                                                                                        
begonia:/ $ wm size reset                                                
begonia:/ $ 
```

### PR DESCRIPTION
**Pull request by yume-chan**
Fixes #1918
Fixes #161
Might affect #4152

Found this API by accident when researching https://github.com/Genymobile/scrcpy/pull/4446#issuecomment-1827164429.

Some devices have a resolution option in their Settings app, and on all devices the resolution can be changed by `adb shell wm size 1080x1920`. This event will react to both cases.

Tested on Xiaomi Mi 11 (Android 13, both system settings and `wm size`), Samsung Galaxy S9 (Android 10, both system settings and `wm size`), Onyx  BOOX Nova Pro (Android 6.0.1, only `wm size`).

### CODE REVIEW

**Review by rom1v — COMMENTED** [review]
Great :+1: I will test later.

**Comment by rom1v** [comment]
For consistency with the other listeners where we use the aidl directly, maybe we could use `IDisplayManagerCallback.aidl`. This is what the wrapper `DisplayListener`s use internally (with an additional `Handler`).

https://github.com/aosp-mirror/platform_frameworks_base/blob/ad73c57d691ad2cfd48b201db6cf8b053d2207ba/core/java/android/hardware/display/DisplayManagerGlobal.java#L1099-L1108

**Comment by yume-chan** [comment]
> maybe we could use `IDisplayManagerCallback.aidl`

I created a new branch to use `IDisplayManager.registerCallback(IDisplayManagerCallback)`: https://github.com/Genymobile/scrcpy/compare/master...yume-chan:scrcpy:feat/resolution-change-2?expand=1

It throws an error when called:

```java
C:\Users\simon\Downloads\scrcpy-win64-v2.3> ./scrcpy -s 0123456789ABCDEF
scrcpy 2.3 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:     -->   (usb)      0123456789ABCDEF            device  NovaPro
INFO:           (usb)              9719052f            device  ONEPLUS_A6000
C:\Users\simon\Downloads\scrcpy-win64-v2.3\scrcpy-server: 1 file pushed, 0 skipped. 10.9 MB/s (66675 bytes in 0.006s)
[server] INFO: Device: [Onyx] Onyx NovaPro (Android 6.0.1)
[server] ERROR: java.lang.reflect.InvocationTargetException
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at com.genymobile.scrcpy.wrappers.DisplayManager.registerCallback(DisplayManager.java:112)
        at com.genymobile.scrcpy.Device.<init>(Device.java:94)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:114)
        at com.genymobile.scrcpy.Server.internalMain(Server.java:244)
        at com.genymobile.scrcpy.Server.main(Server.java:199)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.DisplayManager.registerCallback(DisplayManager.java:110)
        ... 6 more
Caused by: java.lang.SecurityException: The calling process has already registered an IDisplayManagerCallback.
        at android.os.Parcel.readException(Parcel.java:1620)
        at android.os.Parcel.readException(Parcel.java:1573)
        at android.hardware.display.IDisplayManager$Stub$Proxy.registerCallback(IDisplayManager.java:305)
        ... 8 more
ERROR: Server connection failed
```

Until Android 12, one process can only have one `IDisplayManagerCallback`: https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/services/core/java/com/android/server/display/DisplayManagerService.java;l=660-665;drc=b28fb721f5be06818bedc8601e02118ddcbd4739

**Comment by rom1v** [comment]
Oops, it seems this has changed on Android 14:

```
[server] INFO: Device: [Google] google Pixel 8 (Android 14)
[server] ERROR: java.lang.NoSuchMethodException: android.hardware.display.DisplayManagerGlobal.registerDisplayListener [interface android.hardware.display.DisplayManager$DisplayListener, class android.os.Handler]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.hardware.display.DisplayManagerGlobal.registerDisplayListener [interface android.hardware.display.DisplayManager$DisplayListener, class android.os.Handler]
	at com.genymobile.scrcpy.wrappers.DisplayManager.registerDisplayListener(DisplayManager.java:127)
	at com.genymobile.scrcpy.Device.<init>(Device.java:96)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:114)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:244)
	at com.genymobile.scrcpy.Server.main(Server.java:199)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.NoSuchMethodException: android.hardware.display.DisplayManagerGlobal.registerDisplayListener [interface android.hardware.display.DisplayManager$DisplayListener, class android.os.Handler]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.DisplayManager.registerDisplayListener(DisplayManager.java:124)
	... 6 more
```

**Comment by rom1v** [comment]
Oh, this callback is called also on device rotation (and probably also on fold, although I have no foldable device to test).

So we can probably remove the other callbacks completely.

**Comment by rom1v** [comment]
@AdoPi (as author or #3979), could you check that with this PR + this diff:

```diff
diff --git a/server/src/main/java/com/genymobile/scrcpy/Device.java b/server/src/main/java/com/genymobile/scrcpy/Device.java
index 756af86e3..c75e2a8d7 100644
--- a/server/src/main/java/com/genymobile/scrcpy/Device.java
+++ b/server/src/main/java/com/genymobile/scrcpy/Device.java
@@ -106,6 +106,7 @@ public final class Device {
 
             @Override
             public void onDisplayChanged(int displayId) {
+                Ln.i("=== onDisplayChanged(" + displayId + ")");
                 if (Device.this.displayId != displayId) {
                     return;
                 }
```

If you fold the device, is the log printed?

**Comment by rom1v** [comment]
Thank you :+1:

For clarity, I extracted the rotation listener (and fold listener) to separate commits: [`reschange.3`](https://github.com/Genymobile/scrcpy/commits/reschange.3).

I also made minor changes, like removing unused `onDisplayAdded()` and `onDisplayRemoved()`.

However, I just noticed that it does not work at all on Android 14: it builds, but the `onDisplayChanged()` event is never received, either on `wm size` changes or on rotation (on your branch or after my refactors). :disappointed: 

It works correctly on Android <= 13.

**Comment by yume-chan** [comment]
> However, I just noticed that it does not work at all on Android 14

The reason is Android 14 no longer sends display events to "dead" (we don't have any window or service so we are considered as dead) apps: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/display/DisplayManagerService.java;l=2878-2891;drc=d4035b6eb1192f71af7adae47bf17d22c7356fa1

It works if I enable foreground workaround (and keeping it running like camera). https://github.com/Genymobile/scrcpy/pull/4213#issuecomment-1817562149 doesn't work.

**Comment by rom1v** [comment]
@yume-chan For some reason, [`display_changed`](https://github.com/Genymobile/scrcpy/commits/display_changed/) works everywhere, including on Android 14 :tada:

It also fixes: https://github.com/Genymobile/scrcpy/issues/5362#issuecomment-2416219316

**Comment by rom1v** [comment]
> For some reason, [display_changed](https://github.com/Genymobile/scrcpy/commits/display_changed/) works everywhere

Oh no, not everywhere. It works on Android 14 on my device, but not on another tablet with Android 14. I think there are some early Android 14 version which are broken.

I don't know how to handle that properly.

**Comment by rom1v** [comment]
It might have been fixed by https://android.googlesource.com/platform/frameworks/base.git/+/f2daa46634f6a1e5e329041f07a27dbc894d71b2%5E%21/, but the first tag with this commit is `android-15.0.0_r1`, while my device has Android 14, so maybe not.

**Comment by rom1v** [comment]
With this commit, it works on all versions (AFAIK): 6e2613733b1fc3e35ec6df8145a81a392f903ebe

Feedback welcome :wink:

There is a fallback specifically for Android 14 (which still listens to rotation and display fold events), but only until it receives the first `DisplayListener` event (so we can be sure this is an upgrade of Android 14 that works). This avoids to reset the encoding twice (one on rotation event, one on display event).

It's a bit hacky though.

**Comment by rom1v** [comment]
Not so good: `onDisplayChanged()` is also called when the screen turns off/on :disappointed:

**Comment by yume-chan** [comment]
Does display power state change its size? Can we compare the size and only restart when it changes?

**Comment by rom1v** [comment]
Yes, I did that on a local branch.

**Pull request closed without merging**
