### PR TITLE
Press 2x extra mouse button to open settings

### PR DESCRIPTION
**Pull request by brunoais**
Requires #2260

### CODE REVIEW

**Comment by rom1v** [comment]
Merged into `dev`.

**Comment by rom1v** [comment]
A minor inconsistency: with the keyboard shortcut, the settings panel is expanded regardless of the delay between the first <kbd>MOD</kbd>+<kbd>n</kbd> and the second. With the mouse, it only works with a double-click. Maybe it should work with a longer delay too? What do you think?

**Comment by brunoais** [comment]
Sounds good to me. That feature acting consistent between both ways is better.

**Comment by rom1v** [comment]
OK, I noticed this when testing before releasing v1.18. But it's minor, so I still released. It can be fixed later :wink:

**Comment by rom1v** [comment]
> Maybe it should work with a longer delay too?

(Or maybe the keyboard shortcut should only work for a short delay (like a double click), I don't know which is better.)

**Comment by brunoais** [comment]
After thinking for a while. I think both should have the reset after a short delay.
Any ideas on how to achieve that? I don't know SDL API well enough for that.

**Pull request closed without merging**
