### PR TITLE
Add feature: select display to mirror

### PR DESCRIPTION
**Pull request by peanutwolf**
> This is rebased version of https://github.com/Genymobile/scrcpy/pull/1177 PR

@rom1v I was in the middle of rebasing https://github.com/Genymobile/scrcpy/pull/1177 and accidentally deleted remote branch from my fork repository but pushed it back again. Unfortunately github doesn't allow to reopen my previous PR(button is disabled).  Is it possible for you as a maintained to reopen #1177 and close this one to preserve the conversation history?

### CODE REVIEW

**Comment by rom1v** [comment]
Thank you :+1:

I squashed the commits, and applied several changes locally. The result is on branch [`pr1238`](https://github.com/Genymobile/scrcpy/commits/pr1238).

In particular, `setDisplayId()` is not called if `displayId` is 0 (the method might not exist).

Could you please review the changes, and test?

I don't understand what `FLAG_SUPPORTS_PROTECTED_BUFFERS` does? Is it important to check it (just to print a warning)?

**Comment by rom1v** [comment]
When the display does not exist, the server terminates before connecting to the client.

In that case, the client awaited on accept() indefinitely (and we had to Ctrl+C).

It's a problem I have known for a long time, but I never took the time to fix it. I just did it (but I tested only on Linux).

Could you please test (+review) the branch [`threadwait`](https://github.com/Genymobile/scrcpy/commits/threadwait) (it includes your PR) on Windows or Mac? Attempt to execute `scrcpy --display 1234` (an invalid display id). It should terminate properly immediately.

Thank you :)

**Comment by rom1v** [comment]
Arf, on `threadwait`, it does not start on Windows :disappointed:

**Comment by rom1v** [comment]
I fixed the problem a bit differently. Could you test [`threadwait.2`](https://github.com/Genymobile/scrcpy/commits/threadwait.2) please?

**Comment by peanutwolf** [comment]
I've test changes on [threadwait.2](https://github.com/Genymobile/scrcpy/commits/threadwait.2) and it works fine for display_id and server termination features. But the thing is I have Linux machine too and can't test it on Mac or Windows, sorry.

I don't know how exactly MediaCodec works under the hood but what I have noticed is that if display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS then android.media.MediaCodec#dequeueOutputBuffer is never called. Android doc says that absence of this flag means that display is unable to form secure buffers. So maybe it is worth terminating mirroring if display does not have this flag. I couldn't find clear connection, so that is why I used warning instead.

**Comment by rom1v** [comment]
> Android doc says that absence of this flag means that display is unable to form secure buffers.


Oh, what if you pass `false` here:

https://github.com/Genymobile/scrcpy/blob/7bb91638ad80ba20700529cf336ea533d8f058e7/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L163

?

**Comment by peanutwolf** [comment]
I tested it but it has the same behavior even if i pass 'false' argument.

**Comment by rom1v** [comment]
Merged on `dev` branch: 4150eedcdf1652fd131480383850882f95a0ea7d

**Pull request closed without merging**
