### PR TITLE
Set icon and server env paths for meson devenv

### PR DESCRIPTION
**Pull request by ColinKinloch**
This allows users to compile and run the project without root.

```sh
meson setup x
meson compile -C x
meson devenv -C x
scrcpy
```

### CODE REVIEW

**Comment by rom1v** [comment]
Great, I didn't know about `meson devenv`!

I also discovered that since 0.49, you can use the `/` operator for paths instead of `join_paths()`:

```diff
diff --git app/meson.build app/meson.build
index c74ee1021..abef527f5 100644
--- app/meson.build
+++ app/meson.build
@@ -282,6 +282,6 @@ endif
 
 if meson.version().version_compare('>= 0.58.0')
        devenv = environment()
-       devenv.set('SCRCPY_ICON_PATH', join_paths(meson.current_source_dir(), 'data/icon.png'))
+       devenv.set('SCRCPY_ICON_PATH', meson.current_source_dir() / 'data/icon.png'))
        meson.add_devenv(devenv)
 endif
diff --git server/meson.build server/meson.build
index 2e5fa9d2a..8a53656cf 100644
--- server/meson.build
+++ server/meson.build
@@ -26,6 +26,6 @@ endif
 
 if meson.version().version_compare('>= 0.58.0')
        devenv = environment()
-       devenv.set('SCRCPY_SERVER_PATH', join_paths(meson.current_build_dir(), 'scrcpy-server'))
+       devenv.set('SCRCPY_SERVER_PATH', meson.current_build_dir() / 'scrcpy-server'))
        meson.add_devenv(devenv)
 endif
```

- https://mesonbuild.com/Reference-manual_functions.html#join_paths
- https://mesonbuild.com/Syntax.html#string-path-building

**Comment by rom1v** [comment]
Oh, I thought it was ok without bumping because it is in a block checking version >= 0.5.8.

But in fact, it will probably still fail due to a syntax error on 0.48.

So it's probably better to keep it like it is.

**Comment by rom1v** [comment]
> I'm not sure what the 0.48 minimum is based on.

It was bumped by eb8f7a1f288b43e333db12e0f329e7706da5a164.

**Comment by ColinKinloch** [comment]
The commit is from 2020 when Stretch went out of support.
Buster has `0.56.2` and went out of support in 2022.
Maybe it's time 🤷

**Comment by ColinKinloch** [comment]
It looks fine and runs fine. However I didn't run an `meson install`.
There are a couple of unrelated commits on it though.

**Comment by rom1v** [comment]
Thank you. Merged into `dev` :rocket:

**Pull request closed without merging**
